# AUTO-GENERATED by BSD-Cov cook.
clear -all
set fml_dir [file normalize [file dirname [info script]]]
cd $fml_dir
set trace_dir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/ibex_id_stage-ibex_top.u_ibex_core.id_stage_i/stall_mem-stall_multdiv-stall_branch-stall_jump-c815/cmp/cex/traces/cex_000}
file delete -force $trace_dir
file mkdir $trace_dir
analyze -sv12 -f {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/ibex_id_stage-ibex_top.u_ibex_core.id_stage_i/stall_mem-stall_multdiv-stall_branch-stall_jump-c815/cmp/cex/stall_mem-stall_multdiv-stall_branch-stall_jump-c815.cex.f}
elaborate -top {bsdcov_miter_stall_mem_stall_multdiv_stall_branch_stall_jump_c815}
clock clk
reset -none
set_prove_dump_trace_type assert
set per_prop_time 300s
set target_props [get_property_list -include {type assert}]
if {[llength $target_props] == 0} {
  puts "ERROR: no cone miter assertions found"
  exit 1
}
set prop [lindex $target_props 0]
prove -property $prop -asserts -force \
  -per_property_time_limit $per_prop_time \
  -dump_trace \
  -dump_trace_type vcd \
  -dump_trace_dir $trace_dir
report -property $target_props -results -detailed -file {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/ibex_id_stage-ibex_top.u_ibex_core.id_stage_i/stall_mem-stall_multdiv-stall_branch-stall_jump-c815/cmp/cex/log/property.rpt} -force
report -property $target_props -csv -include_type -file {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/ibex_id_stage-ibex_top.u_ibex_core.id_stage_i/stall_mem-stall_multdiv-stall_branch-stall_jump-c815/cmp/cex/log/property.csv} -force
report -summary -file {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/ibex_id_stage-ibex_top.u_ibex_core.id_stage_i/stall_mem-stall_multdiv-stall_branch-stall_jump-c815/cmp/cex/log/summary.rpt} -force
set cex_file [open {cex_properties.list} w]
foreach p $target_props {
  set st [get_status $p]
  if {$st eq "cex" || $st eq "ar_cex"} { puts $cex_file $p }
}
close $cex_file
exit
