// AUTO-GENERATED by BSD-Cov cook.
// Width-aware local helper modules for reduction cells emitted in extracted cone netlists.

module reduce_nor_5(
  input logic a_4_,
  input logic a_3_,
  input logic a_2_,
  input logic a_1_,
  input logic a_0_,
  output logic o
);
  assign o = ~(|({a_4_, a_3_, a_2_, a_1_, a_0_}));
endmodule

module reduce_or_2(
  input logic a_1_,
  input logic a_0_,
  output logic o
);
  assign o = |({a_1_, a_0_});
endmodule

module reduce_or_5(
  input logic a_4_,
  input logic a_3_,
  input logic a_2_,
  input logic a_1_,
  input logic a_0_,
  output logic o
);
  assign o = |({a_4_, a_3_, a_2_, a_1_, a_0_});
endmodule
