// AUTO-GENERATED by BSD-Cov cook.
// Formal miter between extracted RTL cone and trained BSD.
module bsdcov_miter_stall_mem_stall_multdiv_stall_branch_stall_jump_c815 (input logic clk);

  logic branch_in_dec;
  logic branch_not_set;
  logic controller_run;
  logic csr_mstatus_tw_i;
  logic data_ind_timing_i;
  logic debug_mode_o;
  logic div_en_dec;
  logic dret_insn_dec;
  logic ex_valid_i;
  logic id_fsm_q;
  logic illegal_csr_insn_i;
  logic illegal_insn_dec;
  logic instr_fetch_err_i;
  logic instr_valid_i;
  logic jump_in_dec;
  logic lsu_req_dec;
  logic lsu_req_done_i;
  logic lsu_resp_valid_i;
  logic mret_insn_dec;
  logic mult_en_dec;
  logic outstanding_load_wb_i;
  logic outstanding_store_wb_i;
  logic priv_mode_i_0;
  logic priv_mode_i_1;
  logic ready_wb_i;
  logic rf_raddr_a_o_0;
  logic rf_raddr_a_o_1;
  logic rf_raddr_a_o_2;
  logic rf_raddr_a_o_3;
  logic rf_raddr_a_o_4;
  logic rf_raddr_b_o_0;
  logic rf_raddr_b_o_1;
  logic rf_raddr_b_o_2;
  logic rf_raddr_b_o_3;
  logic rf_raddr_b_o_4;
  logic rf_ren_a_dec;
  logic rf_ren_b_dec;
  logic rf_waddr_wb_i_0;
  logic rf_waddr_wb_i_1;
  logic rf_waddr_wb_i_2;
  logic rf_waddr_wb_i_3;
  logic rf_waddr_wb_i_4;
  logic wfi_insn_dec;
  logic stall_mem_rtl;
  logic stall_multdiv_rtl;
  logic stall_branch_rtl;
  logic stall_jump_rtl;
  logic [42:0] bsd_i;
  logic [3:0] bsd_o;
  logic [3:0] rtl_o;

  bsdcov_cone_stall_mem_stall_multdiv_stall_branch_stall_jump_c815 u_rtl_cone (
    .branch_in_dec(branch_in_dec),
    .branch_not_set(branch_not_set),
    .controller_run(controller_run),
    .csr_mstatus_tw_i(csr_mstatus_tw_i),
    .data_ind_timing_i(data_ind_timing_i),
    .debug_mode_o(debug_mode_o),
    .div_en_dec(div_en_dec),
    .dret_insn_dec(dret_insn_dec),
    .ex_valid_i(ex_valid_i),
    .id_fsm_q(id_fsm_q),
    .illegal_csr_insn_i(illegal_csr_insn_i),
    .illegal_insn_dec(illegal_insn_dec),
    .instr_fetch_err_i(instr_fetch_err_i),
    .instr_valid_i(instr_valid_i),
    .jump_in_dec(jump_in_dec),
    .lsu_req_dec(lsu_req_dec),
    .lsu_req_done_i(lsu_req_done_i),
    .lsu_resp_valid_i(lsu_resp_valid_i),
    .mret_insn_dec(mret_insn_dec),
    .mult_en_dec(mult_en_dec),
    .outstanding_load_wb_i(outstanding_load_wb_i),
    .outstanding_store_wb_i(outstanding_store_wb_i),
    .priv_mode_i_0_(priv_mode_i_0),
    .priv_mode_i_1_(priv_mode_i_1),
    .ready_wb_i(ready_wb_i),
    .rf_raddr_a_o_0_(rf_raddr_a_o_0),
    .rf_raddr_a_o_1_(rf_raddr_a_o_1),
    .rf_raddr_a_o_2_(rf_raddr_a_o_2),
    .rf_raddr_a_o_3_(rf_raddr_a_o_3),
    .rf_raddr_a_o_4_(rf_raddr_a_o_4),
    .rf_raddr_b_o_0_(rf_raddr_b_o_0),
    .rf_raddr_b_o_1_(rf_raddr_b_o_1),
    .rf_raddr_b_o_2_(rf_raddr_b_o_2),
    .rf_raddr_b_o_3_(rf_raddr_b_o_3),
    .rf_raddr_b_o_4_(rf_raddr_b_o_4),
    .rf_ren_a_dec(rf_ren_a_dec),
    .rf_ren_b_dec(rf_ren_b_dec),
    .rf_waddr_wb_i_0_(rf_waddr_wb_i_0),
    .rf_waddr_wb_i_1_(rf_waddr_wb_i_1),
    .rf_waddr_wb_i_2_(rf_waddr_wb_i_2),
    .rf_waddr_wb_i_3_(rf_waddr_wb_i_3),
    .rf_waddr_wb_i_4_(rf_waddr_wb_i_4),
    .wfi_insn_dec(wfi_insn_dec),
    .stall_mem(stall_mem_rtl),
    .stall_multdiv(stall_multdiv_rtl),
    .stall_branch(stall_branch_rtl),
    .stall_jump(stall_jump_rtl)
  );

  function_top u_bsd (.i(bsd_i), .o(bsd_o));

  assign bsd_i = {
    branch_in_dec,
    branch_not_set,
    controller_run,
    csr_mstatus_tw_i,
    data_ind_timing_i,
    debug_mode_o,
    div_en_dec,
    dret_insn_dec,
    ex_valid_i,
    id_fsm_q,
    illegal_csr_insn_i,
    illegal_insn_dec,
    instr_fetch_err_i,
    instr_valid_i,
    jump_in_dec,
    lsu_req_dec,
    lsu_req_done_i,
    lsu_resp_valid_i,
    mret_insn_dec,
    mult_en_dec,
    outstanding_load_wb_i,
    outstanding_store_wb_i,
    priv_mode_i_0,
    priv_mode_i_1,
    ready_wb_i,
    rf_raddr_a_o_0,
    rf_raddr_a_o_1,
    rf_raddr_a_o_2,
    rf_raddr_a_o_3,
    rf_raddr_a_o_4,
    rf_raddr_b_o_0,
    rf_raddr_b_o_1,
    rf_raddr_b_o_2,
    rf_raddr_b_o_3,
    rf_raddr_b_o_4,
    rf_ren_a_dec,
    rf_ren_b_dec,
    rf_waddr_wb_i_0,
    rf_waddr_wb_i_1,
    rf_waddr_wb_i_2,
    rf_waddr_wb_i_3,
    rf_waddr_wb_i_4,
    wfi_insn_dec
  };
  assign rtl_o = {
    stall_mem_rtl,
    stall_multdiv_rtl,
    stall_branch_rtl,
    stall_jump_rtl
  };

  // Debug aliases used by JasperGold CEX export and NearRegion seed extraction.
  (* keep *) logic [42:0] i_dbg;
  (* keep *) logic [3:0] o_bsd_dbg;
  (* keep *) logic [3:0] o_rtl_dbg;
  (* keep *) logic mismatch_dbg;
  assign i_dbg = bsd_i;
  assign o_bsd_dbg = bsd_o;
  assign o_rtl_dbg = rtl_o;
  assign mismatch_dbg = (rtl_o !== bsd_o);
  a_bsd_equiv: assert property (@(posedge clk) rtl_o == bsd_o);

endmodule
