// AUTO-GENERATED by BSD-Cov cook.
// Local Verific primitive models for extracted cone netlists.

module BSDCOV_VERIFIC_AND(input logic a0, input logic a1, output logic o);
  assign o = a0 & a1;
endmodule

module BSDCOV_VERIFIC_NAND(input logic a0, input logic a1, output logic o);
  assign o = ~(a0 & a1);
endmodule

module BSDCOV_VERIFIC_OR(input logic a0, input logic a1, output logic o);
  assign o = a0 | a1;
endmodule

module BSDCOV_VERIFIC_NOR(input logic a0, input logic a1, output logic o);
  assign o = ~(a0 | a1);
endmodule

module BSDCOV_VERIFIC_XOR(input logic a0, input logic a1, output logic o);
  assign o = a0 ^ a1;
endmodule

module BSDCOV_VERIFIC_XNOR(input logic a0, input logic a1, output logic o);
  assign o = ~(a0 ^ a1);
endmodule

module BSDCOV_VERIFIC_NOT(input logic i, output logic o);
  assign o = ~i;
endmodule

module BSDCOV_VERIFIC_INV(input logic i, output logic o);
  assign o = ~i;
endmodule

module BSDCOV_VERIFIC_BUF(input logic i, output logic o);
  assign o = i;
endmodule

module BSDCOV_VERIFIC_MUX(
  input logic s,
  input logic c,
  input logic a0,
  input logic a1,
  input logic i0,
  input logic i1,
  input logic a,
  input logic b,
  output logic o
);
  wire lo = (a0 !== 1'bz) ? a0 : ((i0 !== 1'bz) ? i0 : a);
  wire hi = (a1 !== 1'bz) ? a1 : ((i1 !== 1'bz) ? i1 : b);
  wire sel = (c !== 1'bz) ? c : s;
  assign o = sel ? hi : lo;
endmodule

module BSDCOV_VERIFIC_MUX2(
  input logic s,
  input logic c,
  input logic a0,
  input logic a1,
  output logic o
);
  wire sel = (c !== 1'bz) ? c : s;
  assign o = sel ? a1 : a0;
endmodule
