// AUTO-GENERATED by BSD-Cov cook.
// Region-hit assertion properties learned from NearRegion samples.
// Learned regions: 16, emitted unique assertion regions: 14.
module bsdcov_regions_stall_mem_stall_multdiv_stall_branch_stall_jump_c815 (
  input logic clk_i,
  input logic rst_ni,
  input logic branch_in_dec,
  input logic branch_not_set,
  input logic controller_run,
  input logic csr_mstatus_tw_i,
  input logic data_ind_timing_i,
  input logic debug_mode_o,
  input logic div_en_dec,
  input logic dret_insn_dec,
  input logic ex_valid_i,
  input logic id_fsm_q,
  input logic illegal_csr_insn_i,
  input logic illegal_insn_dec,
  input logic instr_fetch_err_i,
  input logic instr_valid_i,
  input logic jump_in_dec,
  input logic lsu_req_dec,
  input logic lsu_req_done_i,
  input logic lsu_resp_valid_i,
  input logic mret_insn_dec,
  input logic mult_en_dec,
  input logic outstanding_load_wb_i,
  input logic outstanding_store_wb_i,
  input logic priv_mode_i_0,
  input logic priv_mode_i_1,
  input logic ready_wb_i,
  input logic rf_raddr_a_o_0,
  input logic rf_raddr_a_o_1,
  input logic rf_raddr_a_o_2,
  input logic rf_raddr_a_o_3,
  input logic rf_raddr_a_o_4,
  input logic rf_raddr_b_o_0,
  input logic rf_raddr_b_o_1,
  input logic rf_raddr_b_o_2,
  input logic rf_raddr_b_o_3,
  input logic rf_raddr_b_o_4,
  input logic rf_ren_a_dec,
  input logic rf_ren_b_dec,
  input logic rf_waddr_wb_i_0,
  input logic rf_waddr_wb_i_1,
  input logic rf_waddr_wb_i_2,
  input logic rf_waddr_wb_i_3,
  input logic rf_waddr_wb_i_4,
  input logic wfi_insn_dec
);

  // focus_outputs: stall_mem
  wire R_unique_000_hit =
      (lsu_resp_valid_i == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_000: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_000_hit);

  // focus_outputs: stall_mem
  wire R_unique_001_hit =
      (lsu_req_done_i == 1'b0) &&
      (rf_raddr_b_o_1 == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_001: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_001_hit);

  // focus_outputs: stall_mem
  wire R_unique_002_hit =
      (lsu_req_done_i == 1'b0) &&
      (rf_raddr_a_o_4 == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_002: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_002_hit);

  // focus_outputs: stall_mem
  wire R_unique_003_hit =
      (lsu_req_done_i == 1'b0) &&
      (priv_mode_i_0 == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_003: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_003_hit);

  // focus_outputs: stall_mem
  wire R_unique_004_hit =
      (lsu_req_done_i == 1'b0) &&
      (rf_ren_a_dec == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_004: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_004_hit);

  // focus_outputs: stall_mem
  wire R_unique_005_hit =
      (lsu_req_done_i == 1'b0) &&
      (outstanding_load_wb_i == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_005: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_005_hit);

  // focus_outputs: stall_mem
  wire R_unique_006_hit =
      (lsu_req_done_i == 1'b0) &&
      (data_ind_timing_i == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_006: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_006_hit);

  // focus_outputs: stall_mem
  wire R_unique_007_hit =
      (lsu_req_done_i == 1'b0) &&
      (rf_raddr_b_o_0 == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_007: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_007_hit);

  // focus_outputs: stall_mem
  wire R_unique_008_hit =
      (lsu_req_done_i == 1'b0) &&
      (rf_ren_b_dec == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_008: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_008_hit);

  // focus_outputs: stall_mem
  wire R_unique_009_hit =
      (lsu_req_done_i == 1'b0) &&
      (branch_in_dec == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_009: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_009_hit);

  // focus_outputs: stall_mem
  wire R_unique_010_hit =
      (lsu_req_done_i == 1'b0) &&
      (ex_valid_i == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_010: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_010_hit);

  // focus_outputs: stall_mem
  wire R_unique_011_hit =
      (lsu_req_done_i == 1'b0) &&
      (mult_en_dec == 1'b0);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_011: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_011_hit);

  // focus_outputs: stall_mem
  wire R_unique_012_hit =
      (lsu_req_done_i == 1'b0) &&
      (instr_valid_i == 1'b1) &&
      (lsu_req_dec == 1'b1);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_012: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_012_hit);

  // focus_outputs: stall_multdiv, stall_branch, stall_jump
  wire R_unique_013_hit =
      (branch_not_set == 1'b1);
  AST_BSDCOV_stall_mem_stall_multdiv_stall_branch_stall_jump_c815_R_unique_013: assert property (@(posedge clk_i) disable iff (!rst_ni) !R_unique_013_hit);

endmodule

bind ibex_id_stage bsdcov_regions_stall_mem_stall_multdiv_stall_branch_stall_jump_c815 u_bsdcov_regions_stall_mem_stall_multdiv_stall_branch_stall_jump_c815 (
  .clk_i(clk_i),
  .rst_ni(rst_ni),
  .branch_in_dec(branch_in_dec),
  .branch_not_set(branch_not_set),
  .controller_run(controller_run),
  .csr_mstatus_tw_i(csr_mstatus_tw_i),
  .data_ind_timing_i(data_ind_timing_i),
  .debug_mode_o(debug_mode_o),
  .div_en_dec(div_en_dec),
  .dret_insn_dec(dret_insn_dec),
  .ex_valid_i(ex_valid_i),
  .id_fsm_q(id_fsm_q),
  .illegal_csr_insn_i(illegal_csr_insn_i),
  .illegal_insn_dec(illegal_insn_dec),
  .instr_fetch_err_i(instr_fetch_err_i),
  .instr_valid_i(instr_valid_i),
  .jump_in_dec(jump_in_dec),
  .lsu_req_dec(lsu_req_dec),
  .lsu_req_done_i(lsu_req_done_i),
  .lsu_resp_valid_i(lsu_resp_valid_i),
  .mret_insn_dec(mret_insn_dec),
  .mult_en_dec(mult_en_dec),
  .outstanding_load_wb_i(outstanding_load_wb_i),
  .outstanding_store_wb_i(outstanding_store_wb_i),
  .priv_mode_i_0(priv_mode_i[0]),
  .priv_mode_i_1(priv_mode_i[1]),
  .ready_wb_i(ready_wb_i),
  .rf_raddr_a_o_0(rf_raddr_a_o[0]),
  .rf_raddr_a_o_1(rf_raddr_a_o[1]),
  .rf_raddr_a_o_2(rf_raddr_a_o[2]),
  .rf_raddr_a_o_3(rf_raddr_a_o[3]),
  .rf_raddr_a_o_4(rf_raddr_a_o[4]),
  .rf_raddr_b_o_0(rf_raddr_b_o[0]),
  .rf_raddr_b_o_1(rf_raddr_b_o[1]),
  .rf_raddr_b_o_2(rf_raddr_b_o[2]),
  .rf_raddr_b_o_3(rf_raddr_b_o[3]),
  .rf_raddr_b_o_4(rf_raddr_b_o[4]),
  .rf_ren_a_dec(rf_ren_a_dec),
  .rf_ren_b_dec(rf_ren_b_dec),
  .rf_waddr_wb_i_0(rf_waddr_wb_i[0]),
  .rf_waddr_wb_i_1(rf_waddr_wb_i[1]),
  .rf_waddr_wb_i_2(rf_waddr_wb_i[2]),
  .rf_waddr_wb_i_3(rf_waddr_wb_i[3]),
  .rf_waddr_wb_i_4(rf_waddr_wb_i[4]),
  .wfi_insn_dec(wfi_insn_dec)
);
