// AUTO-GENERATED by BSD-Cov verific_conegen.
// Target module: ibex_id_stage
// Source spec: /home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/module_bind/stall_mem-stall_ld_hz-stall_multdiv-stall_branch-stall_jump-1111/cone_spec.resolved.json

module bsdcov_io_dump_if_stall_mem_stall_ld_hz_stall_multdiv_stall_branch_stall_jump_1111 (
  input logic clk_i,
  input logic rst_ni,
  input logic branch_in_dec,
  input logic branch_not_set,
  input logic controller_run,
  input logic csr_mstatus_tw_i,
  input logic data_ind_timing_i,
  input logic debug_mode_o,
  input logic div_en_dec,
  input logic dret_insn_dec,
  input logic ex_valid_i,
  input logic id_fsm_q,
  input logic illegal_csr_insn_i,
  input logic illegal_insn_dec,
  input logic instr_fetch_err_i,
  input logic instr_valid_i,
  input logic jump_in_dec,
  input logic lsu_req_dec,
  input logic lsu_req_done_i,
  input logic lsu_resp_valid_i,
  input logic mret_insn_dec,
  input logic mult_en_dec,
  input logic outstanding_load_wb_i,
  input logic outstanding_store_wb_i,
  input logic [1:0] priv_mode_i_0_,
  input logic [1:0] priv_mode_i_1_,
  input logic ready_wb_i,
  input logic [4:0] rf_raddr_a_o_0_,
  input logic [4:0] rf_raddr_a_o_1_,
  input logic [4:0] rf_raddr_a_o_2_,
  input logic [4:0] rf_raddr_a_o_3_,
  input logic [4:0] rf_raddr_a_o_4_,
  input logic [4:0] rf_raddr_b_o_0_,
  input logic [4:0] rf_raddr_b_o_1_,
  input logic [4:0] rf_raddr_b_o_2_,
  input logic [4:0] rf_raddr_b_o_3_,
  input logic [4:0] rf_raddr_b_o_4_,
  input logic rf_ren_a_dec,
  input logic rf_ren_b_dec,
  input logic [4:0] rf_waddr_wb_i_0_,
  input logic [4:0] rf_waddr_wb_i_1_,
  input logic [4:0] rf_waddr_wb_i_2_,
  input logic [4:0] rf_waddr_wb_i_3_,
  input logic [4:0] rf_waddr_wb_i_4_,
  input logic wfi_insn_dec,
  input logic stall_mem,
  input logic stall_ld_hz,
  input logic stall_multdiv,
  input logic stall_branch,
  input logic stall_jump
);

  int fd;
  bit trace_en;
  string trace_base;
  string trace_file;

  initial begin
    fd = 0;
    trace_en = $test$plusargs("bsdcov_io_dump");
    if (trace_en) begin
      if (!$value$plusargs("bsdcov_trace_base=%s", trace_base)) begin
        trace_base = "bsdcov_trace";
      end
      trace_file = {trace_base, "_stall_mem-stall_ld_hz-stall_multdiv-stall_branch-stall_jump-1111.io_samples.csv"};
      fd = $fopen(trace_file, "w");
      if (fd == 0) begin
        $display("BSD-COV ERROR: failed to open %s", trace_file);
      end else begin
        $display("BSD-COV: writing IO trace to %s", trace_file);
        $fwrite(fd, "branch_in_dec,branch_not_set,controller_run,csr_mstatus_tw_i,data_ind_timing_i,debug_mode_o,div_en_dec,dret_insn_dec,ex_valid_i,id_fsm_q,illegal_csr_insn_i,illegal_insn_dec,instr_fetch_err_i,instr_valid_i,jump_in_dec,lsu_req_dec,lsu_req_done_i,lsu_resp_valid_i,mret_insn_dec,mult_en_dec,outstanding_load_wb_i,outstanding_store_wb_i,priv_mode_i_0_,priv_mode_i_1_,ready_wb_i,rf_raddr_a_o_0_,rf_raddr_a_o_1_,rf_raddr_a_o_2_,rf_raddr_a_o_3_,rf_raddr_a_o_4_,rf_raddr_b_o_0_,rf_raddr_b_o_1_,rf_raddr_b_o_2_,rf_raddr_b_o_3_,rf_raddr_b_o_4_,rf_ren_a_dec,rf_ren_b_dec,rf_waddr_wb_i_0_,rf_waddr_wb_i_1_,rf_waddr_wb_i_2_,rf_waddr_wb_i_3_,rf_waddr_wb_i_4_,wfi_insn_dec,stall_mem,stall_ld_hz,stall_multdiv,stall_branch,stall_jump\n");
      end
    end
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
    end else if (trace_en && fd != 0 && 1'b1) begin
      $fwrite(fd, "%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d\n",
          branch_in_dec,
          branch_not_set,
          controller_run,
          csr_mstatus_tw_i,
          data_ind_timing_i,
          debug_mode_o,
          div_en_dec,
          dret_insn_dec,
          ex_valid_i,
          id_fsm_q,
          illegal_csr_insn_i,
          illegal_insn_dec,
          instr_fetch_err_i,
          instr_valid_i,
          jump_in_dec,
          lsu_req_dec,
          lsu_req_done_i,
          lsu_resp_valid_i,
          mret_insn_dec,
          mult_en_dec,
          outstanding_load_wb_i,
          outstanding_store_wb_i,
          priv_mode_i_0_,
          priv_mode_i_1_,
          ready_wb_i,
          rf_raddr_a_o_0_,
          rf_raddr_a_o_1_,
          rf_raddr_a_o_2_,
          rf_raddr_a_o_3_,
          rf_raddr_a_o_4_,
          rf_raddr_b_o_0_,
          rf_raddr_b_o_1_,
          rf_raddr_b_o_2_,
          rf_raddr_b_o_3_,
          rf_raddr_b_o_4_,
          rf_ren_a_dec,
          rf_ren_b_dec,
          rf_waddr_wb_i_0_,
          rf_waddr_wb_i_1_,
          rf_waddr_wb_i_2_,
          rf_waddr_wb_i_3_,
          rf_waddr_wb_i_4_,
          wfi_insn_dec,
          stall_mem,
          stall_ld_hz,
          stall_multdiv,
          stall_branch,
          stall_jump
      );
    end
  end

  final begin
    if (trace_en && fd != 0) $fclose(fd);
  end

endmodule
