#!/usr/bin/env python3
"""Generate BSD-Cov RISC-V instruction sequences with riscv-dv.

This script is intentionally scoped to instruction generation only.  It wraps the
in-repository riscv-dv flow and normalizes the generated assembly files under
``dv/bsdcov/riscvdv/assembly``.

Default behavior preserves the simple user mode:

  rand_instr.py --seed 1 --num 1000

which produces:

  riscvdv/assembly/seq.1.1000.S

For coverage-prefix experiments, pass ``--chunk-size``.  This follows the
"independent standalone tests" semantics: each chunk is generated by riscv-dv as
its own standalone assembly test with ``chunk_size`` target instructions.  The
chunks are ordered deterministically for later cumulative coverage prefix merge.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class ChunkInfo:
    index: int
    instr_count: int
    seed: int
    asm: str


def _repo_root() -> Path:
    # dv/bsdcov/scripts/rand_instr.py -> ibex repo root
    return Path(__file__).resolve().parents[3]


def _bsdcov_dir() -> Path:
    return Path(__file__).resolve().parents[1]


def _timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def _positive_int(value: str) -> int:
    try:
        parsed = int(value, 0)
    except ValueError as err:
        raise argparse.ArgumentTypeError(f"expected integer, got {value!r}") from err
    if parsed <= 0:
        raise argparse.ArgumentTypeError(f"expected positive integer, got {value!r}")
    return parsed


def _nonnegative_int(value: str) -> int:
    try:
        parsed = int(value, 0)
    except ValueError as err:
        raise argparse.ArgumentTypeError(f"expected integer, got {value!r}") from err
    if parsed < 0:
        raise argparse.ArgumentTypeError(f"expected non-negative integer, got {value!r}")
    return parsed


def _write_text(path: Path, text: str, *, force: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force and path.read_text(encoding="utf-8") != text:
        raise RuntimeError(f"{path} already exists; pass --force to overwrite")
    path.write_text(text, encoding="utf-8")


def _copy_file(src: Path, dst: Path, *, force: bool) -> None:
    if not src.exists():
        raise RuntimeError(f"expected generated assembly file is missing: {src}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() and not force and dst.read_bytes() != src.read_bytes():
        raise RuntimeError(f"{dst} already exists; pass --force to overwrite")
    shutil.copy2(src, dst)


def _build_pythonpath(repo_root: Path) -> str:
    core_ibex = repo_root / "dv" / "uvm" / "core_ibex"
    riscvdv_root = repo_root / "vendor" / "google_riscv-dv"
    paths = [
        repo_root,
        repo_root / "util",
        core_ibex / "scripts",
        core_ibex / "riscv_dv_extension",
        core_ibex / "yaml",
        riscvdv_root,
        riscvdv_root / "scripts",
        riscvdv_root / "pygen",
        riscvdv_root / "pygen" / "pygen_src",
    ]
    existing = os.environ.get("PYTHONPATH", "")
    if existing:
        paths.extend(Path(item) for item in existing.split(os.pathsep) if item)
    return os.pathsep.join(str(path) for path in paths)


def _default_env(repo_root: Path) -> dict[str, str]:
    env = os.environ.copy()
    env["PYTHONPATH"] = _build_pythonpath(repo_root)
    env.setdefault("IBEX_ROOT", str(repo_root))
    env.setdefault("PRJ_DIR", str(repo_root))
    env.setdefault("LOWRISC_IP_DIR", str(repo_root / "vendor" / "lowrisc_ip"))
    env.setdefault("DUT_TOP", "ibex_top")
    env.setdefault("dv_root", str(repo_root / "dv"))
    return env


def _chunk_instruction_counts(total: int, chunk_size: int | None) -> list[int]:
    if chunk_size is None:
        return [total]
    num_chunks = math.ceil(total / chunk_size)
    counts = []
    remaining = total
    for _ in range(num_chunks):
        count = min(chunk_size, remaining)
        counts.append(count)
        remaining -= count
    return counts


def _chunk_output_name(seed: int, total: int, idx: int, num_chunks: int, *, single: bool) -> str:
    if single:
        return f"seq.{seed}.{total}.S"
    return f"seq.{seed}.{total}.chunk_{idx:04d}.of_{num_chunks:04d}.S"


def _test_name(seed: int, total: int, idx: int) -> str:
    return f"bsdcov_seq_{seed}_{total}_chunk_{idx:04d}"


def _make_testlist(
    *,
    path: Path,
    test_name: str,
    instr_count: int,
    gen_test: str,
    rtl_test: str,
    boot_mode: str,
    num_sub_program: int,
    extra_gen_opts: Iterable[str],
    force: bool,
) -> None:
    opts = [
        f"+instr_cnt={instr_count}",
        f"+num_of_sub_program={num_sub_program}",
        f"+boot_mode={boot_mode}",
    ]
    opts.extend(extra_gen_opts)

    body = [
        "# AUTO-GENERATED by dv/bsdcov/scripts/rand_instr.py.",
        "# Each entry is one standalone riscv-dv chunk test.",
        f"- test: {test_name}",
        "  description: BSD-Cov independent instruction chunk generated for cumulative coverage experiments",
        "  iterations: 1",
        f"  gen_test: {gen_test}",
        "  gen_opts: >",
    ]
    body.extend(f"    {opt}" for opt in opts)
    body.extend([
        f"  rtl_test: {rtl_test}",
        "",
    ])
    _write_text(path, "\n".join(body), force=force)


def _run_riscvdv(
    *,
    repo_root: Path,
    testlist: Path,
    test_name: str,
    out_dir: Path,
    seed: int,
    generator_simulator: str,
    target: str,
    isa: str,
    mabi: str,
    timeout_s: int,
    log_file: Path,
    verbose: bool,
    dry_run: bool,
) -> None:
    riscvdv_root = repo_root / "vendor" / "google_riscv-dv"
    core_ibex = repo_root / "dv" / "uvm" / "core_ibex"
    custom_target = core_ibex / "riscv_dv_extension"
    csr_yaml = custom_target / "csr_description.yaml"

    cmd = [
        sys.executable,
        str(riscvdv_root / "run.py"),
        "--testlist",
        str(testlist),
        "--test",
        test_name,
        "--steps",
        "gen",
        "--simulator",
        generator_simulator,
        "--target",
        target,
        "--custom_target",
        str(custom_target),
        "--csr_yaml",
        str(csr_yaml),
        "--mabi",
        mabi,
        "--isa",
        isa,
        "--seed",
        str(seed),
        "--output",
        str(out_dir),
        "--gcc_opts=-mno-strict-align",
    ]
    if verbose:
        cmd.append("--verbose")

    cmd_str = " ".join(str(item) for item in cmd)
    log_file.parent.mkdir(parents=True, exist_ok=True)
    if dry_run:
        log_file.write_text("DRY-RUN: " + cmd_str + "\n", encoding="utf-8")
        return

    env = _default_env(repo_root)
    with log_file.open("w", encoding="utf-8") as log:
        log.write("Running riscv-dv command:\n")
        log.write(cmd_str + "\n\n")
        log.flush()
        result = subprocess.run(
            cmd,
            cwd=str(repo_root),
            env=env,
            text=True,
            stdout=log,
            stderr=subprocess.STDOUT,
            timeout=timeout_s,
            check=False,
        )
    if result.returncode != 0:
        raise RuntimeError(f"riscv-dv generation failed for {test_name}; see {log_file}")


def _generated_asm_path(out_dir: Path, test_name: str) -> Path:
    return out_dir / "asm_test" / f"{test_name}_0.S"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate BSD-Cov riscv-dv standalone instruction sequence chunks.")
    parser.add_argument("--seed", type=_nonnegative_int, required=True,
                        help="Base random seed. Chunk i uses seed+i.")
    parser.add_argument("--num", type=_positive_int, required=True,
                        help="Total target instruction count across all chunks.")
    parser.add_argument("--chunk-size", type=_positive_int, default=None,
                        help="Generate independent standalone chunks of this size. If omitted, generate one .S.")
    parser.add_argument("--generator-simulator", default="pyflow",
                        help="riscv-dv generator simulator, e.g. pyflow, xlm, vcs. Default: pyflow")
    parser.add_argument("--target", default="rv32imc",
                        help="riscv-dv target. Default: rv32imc")
    parser.add_argument("--isa", default="rv32imc",
                        help="ISA string passed to riscv-dv. Default: rv32imc")
    parser.add_argument("--mabi", default="ilp32",
                        help="MABI passed to riscv-dv. Default: ilp32")
    parser.add_argument("--gen-test", default="riscv_instr_base_test",
                        help="riscv-dv UVM generator test. Default: riscv_instr_base_test")
    parser.add_argument("--rtl-test", default="core_ibex_base_test",
                        help="Ibex RTL test name recorded in generated testlist. Default: core_ibex_base_test")
    parser.add_argument("--boot-mode", default="m",
                        help="riscv-dv +boot_mode value. Default: m")
    parser.add_argument("--num-of-sub-program", type=_nonnegative_int, default=5,
                        help="riscv-dv +num_of_sub_program value. Default: 5")
    parser.add_argument("--gen-opt", action="append", default=[],
                        help="Extra raw riscv-dv +option to append to gen_opts. Can be repeated.")
    parser.add_argument("--out-dir", type=Path, default=None,
                        help="Override output directory. Default: dv/bsdcov/riscvdv")
    parser.add_argument("--timeout-s", type=_positive_int, default=1200,
                        help="Per-chunk riscv-dv generation timeout in seconds. Default: 1200")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing generated files.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Write testlists and command logs without invoking riscv-dv.")
    parser.add_argument("--verbose", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    repo_root = _repo_root()
    bsdcov_dir = _bsdcov_dir()
    riscvdv_dir = args.out_dir.resolve() if args.out_dir else (bsdcov_dir / "riscvdv")

    assembly_dir = riscvdv_dir / "assembly"
    work_root = riscvdv_dir / "work" / f"seq.{args.seed}.{args.num}"
    testlist_dir = riscvdv_dir / "testlists"
    log_dir = riscvdv_dir / "logs"
    metadata_dir = riscvdv_dir / "metadata"

    for path in [assembly_dir, work_root, testlist_dir, log_dir, metadata_dir]:
        path.mkdir(parents=True, exist_ok=True)

    chunk_counts = _chunk_instruction_counts(args.num, args.chunk_size)
    num_chunks = len(chunk_counts)
    single = num_chunks == 1

    chunk_infos: list[ChunkInfo] = []
    chunk_list_file = assembly_dir / f"seq.{args.seed}.{args.num}.chunks.f"

    for idx, instr_count in enumerate(chunk_counts):
        chunk_seed = args.seed + idx
        test_name = _test_name(args.seed, args.num, idx)
        testlist = testlist_dir / f"{test_name}.yaml"
        out_dir = work_root / f"chunk_{idx:04d}"
        log_file = log_dir / f"rand_instr.{args.seed}.{args.num}.chunk_{idx:04d}.log"
        dst = assembly_dir / _chunk_output_name(args.seed, args.num, idx, num_chunks, single=single)

        _make_testlist(
            path=testlist,
            test_name=test_name,
            instr_count=instr_count,
            gen_test=args.gen_test,
            rtl_test=args.rtl_test,
            boot_mode=args.boot_mode,
            num_sub_program=args.num_of_sub_program,
            extra_gen_opts=args.gen_opt,
            force=args.force,
        )

        _run_riscvdv(
            repo_root=repo_root,
            testlist=testlist,
            test_name=test_name,
            out_dir=out_dir,
            seed=chunk_seed,
            generator_simulator=args.generator_simulator,
            target=args.target,
            isa=args.isa,
            mabi=args.mabi,
            timeout_s=args.timeout_s,
            log_file=log_file,
            verbose=args.verbose,
            dry_run=args.dry_run,
        )

        src = _generated_asm_path(out_dir, test_name)
        if args.dry_run:
            dst.write_text(
                "// DRY-RUN placeholder generated by rand_instr.py\n"
                f"// Would copy from: {src}\n",
                encoding="utf-8",
            )
        else:
            _copy_file(src, dst, force=args.force)

        chunk_infos.append(ChunkInfo(
            index=idx,
            instr_count=instr_count,
            seed=chunk_seed,
            asm=str(dst.resolve()),
        ))
        print(dst)

    _write_text(
        chunk_list_file,
        "".join(f"{info.asm}\n" for info in chunk_infos),
        force=True,
    )

    metadata = {
        "generated_at": _timestamp(),
        "generator": "riscv-dv",
        "semantics": "independent_standalone_tests",
        "seed": args.seed,
        "total_instr": args.num,
        "chunk_size": args.chunk_size if args.chunk_size else args.num,
        "num_chunks": num_chunks,
        "generator_simulator": args.generator_simulator,
        "target": args.target,
        "isa": args.isa,
        "mabi": args.mabi,
        "gen_test": args.gen_test,
        "rtl_test": args.rtl_test,
        "boot_mode": args.boot_mode,
        "num_of_sub_program": args.num_of_sub_program,
        "extra_gen_opts": args.gen_opt,
        "chunk_list": str(chunk_list_file.resolve()),
        "chunks": [asdict(info) for info in chunk_infos],
    }
    metadata_path = metadata_dir / f"seq.{args.seed}.{args.num}.json"
    _write_text(metadata_path, json.dumps(metadata, indent=2) + "\n", force=True)

    print(f"Wrote chunk list: {chunk_list_file}")
    print(f"Wrote metadata: {metadata_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
