#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import os
import random
import re
import subprocess
import tempfile
import time
from pathlib import Path

DEFAULT_VERDI_HOME = "/home/lvzhengyang/workspace/synopsys/verdi/T-2022.06"
DEFAULT_XRUN = "/home/lvzhengyang/workspace/cadence/XCELIUM2509/tools.lnx86/bin/xrun"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract BSD-Cov cone IO samples from FSDB")
    parser.add_argument("--fsdb", type=Path, required=True)
    parser.add_argument("--proj", type=Path, required=True)
    parser.add_argument("--verdi-home", type=Path,
                        default=Path(os.environ.get("VERDI_HOME", DEFAULT_VERDI_HOME)))
    parser.add_argument("--random-num", type=int, default=0,
                        help="number of new unique random cone inputs to simulate")
    parser.add_argument("--seed", type=int, help="random seed (defaults to current time)")
    return parser.parse_args()


def parse_cone(cone_dir: Path) -> tuple[list[str], str, dict[str, str]]:
    io_dir = cone_dir / "io_dump"
    interface = io_dir / f"{cone_dir.name}.io_dump_if.sv"
    bind = io_dir / f"{cone_dir.name}.io_dump.bind.sv"
    if not interface.exists() or not bind.exists():
        raise RuntimeError("missing io_dump interface or bind")

    interface_text = interface.read_text(encoding="utf-8", errors="ignore")
    header_match = re.search(r'\$fwrite\(fd,\s*"([^"\\]*\\n)"\);', interface_text)
    if not header_match:
        raise RuntimeError(f"cannot parse CSV header from {interface}")
    header = header_match.group(1)[:-2].split(",")

    bind_text = bind.read_text(encoding="utf-8", errors="ignore")
    target_match = re.search(r"\bbind\s+([^\s]+)\s+[^\s]+\s+[^\s]+\s*\(", bind_text)
    if not target_match:
        raise RuntimeError(f"cannot parse bind target from {bind}")
    target = target_match.group(1)
    connections = dict(re.findall(r"\.([A-Za-z_$][\w$]*)\s*\(\s*([^()]+?)\s*\)", bind_text))
    missing = [name for name in ["clk_i", *header] if name not in connections]
    if missing:
        raise RuntimeError(f"missing bind connection(s): {', '.join(missing)}")
    return header, target, connections


def fsdb_path(target: str, expression: str) -> str:
    hierarchy = target.replace(".", "/")
    signal = expression.strip().replace(".", "/")
    return f"/{hierarchy}/{signal}"


def cone_outputs(cone_dir: Path, header: list[str]) -> list[str]:
    spec_path = cone_dir / "cone_spec.resolved.json"
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    items = spec.get("cone", {}).get("outputs", []) or spec.get("endpoints", [])
    outputs = [re.sub(r"\W", "_", str(item.get("name", "")).strip()) for item in items]
    outputs = [name for name in outputs if name in header]
    if not outputs:
        raise RuntimeError(f"cannot determine cone outputs from {spec_path}")
    return outputs


def stable_cone_seed(seed: int, cone_name: str) -> int:
    value = seed & ((1 << 64) - 1)
    for byte in cone_name.encode("utf-8"):
        value = ((value ^ byte) * 1099511628211) & ((1 << 64) - 1)
    return value


def write_reduce_helpers(path: Path, cone_text: str) -> None:
    modules = sorted(set(re.findall(r"\b(reduce_(and|or|xor|nand|nor|xnor)_(\d+))\s+\w+\s*\(", cone_text)))
    lines = ["// AUTO-GENERATED by BSD-Cov gen_io.", ""]
    for module, op, width_text in modules:
        width = int(width_text)
        ports = [f"  input logic a_{idx}_" for idx in range(width - 1, -1, -1)]
        lines.append(f"module {module}(")
        lines.extend(line + "," for line in ports)
        lines += ["  output logic o", ");"]
        joined = ", ".join(f"a_{idx}_" for idx in range(width - 1, -1, -1))
        expr = {"and": "&", "or": "|", "xor": "^", "nand": "~&",
                "nor": "~|", "xnor": "~^"}[op]
        lines += [f"  assign o = {expr}({{{joined}}});", "endmodule", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def simulate_random_inputs(cone_dir: Path, header: list[str], outputs: list[str],
                           existing_rows: list[list[str]], random_num: int, seed: int,
                           log_dir: Path) -> tuple[list[list[str]], dict[str, object]]:
    if random_num == 0:
        input_count = len(header) - len(outputs)
        return [], {"random_requested": 0, "random_generated": 0,
                    "input_width": input_count, "input_space_size": 1 << input_count}

    inputs = [name for name in header if name not in outputs]
    cone_sv = cone_dir / f"{cone_dir.name}.sv"
    cone_text = cone_sv.read_text(encoding="utf-8", errors="ignore")
    # Extracted IO columns are currently scalarized. Refuse silently-wrong vector packing.
    module_match = re.search(r"\bmodule\s+\w+\s*\((.*?)\);", cone_text, re.DOTALL)
    if not module_match:
        raise RuntimeError(f"cannot parse cone module ports from {cone_sv}")
    vector_ports = set(re.findall(r"\b(?:input|output)\s+logic\s*\[[^]]+\]\s+(\w+)", module_match.group(1)))
    if vector_ports.intersection(header):
        raise RuntimeError("random cone simulation does not yet support non-scalar IO columns")

    input_width = len(inputs)
    input_space = 1 << input_width
    input_indices = [header.index(name) for name in inputs]
    existing = {tuple(row[idx] for idx in input_indices) for row in existing_rows}
    available = input_space - len(existing)
    if random_num > available:
        raise RuntimeError(
            f"requested {random_num} new unique inputs, but only {available} remain "
            f"in the {input_space}-value input space"
        )
    candidates = [value for value in range(input_space)
                  if tuple(f"{value:0{input_width}b}") not in existing]
    rng = random.Random(stable_cone_seed(seed, cone_dir.name))
    selected = rng.sample(candidates, random_num)

    sim_dir = log_dir / cone_dir.name / "random_sim"
    sim_dir.mkdir(parents=True, exist_ok=True)
    input_hex = sim_dir / "input.hex"
    output_csv = sim_dir / "output.csv"
    tb = sim_dir / "random_tb.sv"
    helpers = sim_dir / "reduce_helpers.sv"
    files_f = sim_dir / "files.f"
    run_log = sim_dir / "xrun.log"
    input_hex.write_text("".join(f"{value:x}\n" for value in selected), encoding="utf-8")
    write_reduce_helpers(helpers, cone_text)

    module = re.search(r"\bmodule\s+(\w+)", cone_text).group(1)
    declarations = [f"  logic {name};" for name in header]
    connections = [f"    .{name}({name})" for name in header]
    tb_lines = [
        "// AUTO-GENERATED by BSD-Cov gen_io.",
        "`timescale 1ns/1ps",
        "module bsdcov_random_cone_tb;",
        f"  localparam int IW = {input_width};",
        f"  localparam int NUM = {random_num};",
        "  logic [IW-1:0] vectors [0:NUM-1];",
        *declarations,
        "  string input_path;",
        "  string output_path;",
        "  int fd;",
        f"  {module} dut (",
        *(line + ("," if idx + 1 < len(connections) else "")
          for idx, line in enumerate(connections)),
        "  );",
        "  initial begin",
        "    if (!$value$plusargs(\"INPUT_HEX=%s\", input_path)) $fatal(1, \"missing INPUT_HEX\");",
        "    if (!$value$plusargs(\"OUTPUT_CSV=%s\", output_path)) $fatal(1, \"missing OUTPUT_CSV\");",
        "    $readmemh(input_path, vectors);",
        "    fd = $fopen(output_path, \"w\");",
        "    if (fd == 0) $fatal(1, \"failed to open output CSV\");",
        f"    $fwrite(fd, \"{','.join(header)}\\n\");",
        "    for (int idx = 0; idx < NUM; idx++) begin",
        f"      {{{', '.join(inputs)}}} = vectors[idx];",
        "      #1;",
        f"      $fwrite(fd, \"{','.join(['%0b'] * len(header))}\\n\",",
        "        " + ", ".join(header) + ");",
        "    end",
        "    $fclose(fd);",
        "    $finish;",
        "  end",
        "endmodule",
        "",
    ]
    tb.write_text("\n".join(tb_lines), encoding="utf-8")
    repo_root = Path(__file__).resolve().parents[6]
    primitives = repo_root / "thirdparty/verific/example_designs/verilog/verificmodels.v"
    files_f.write_text("\n".join(map(str, [primitives, helpers, cone_sv, tb])) + "\n",
                       encoding="utf-8")
    xrun = os.environ.get("BSDCOV_XRUN", DEFAULT_XRUN)
    cmd = [xrun, "-64bit", "-sv", "-timescale", "1ns/1ps", "-f", str(files_f),
           "-top", "bsdcov_random_cone_tb",
           "-xmlibdirname", str(sim_dir / "xcelium.d"),
           f"+INPUT_HEX={input_hex}", f"+OUTPUT_CSV={output_csv}"]
    (sim_dir / "xrun.args.txt").write_text("\n".join(cmd) + "\n", encoding="utf-8")
    sim_env = os.environ.copy()
    sim_env.setdefault("CDS_LIC_FILE", "/home/lvzhengyang/workspace/cadence/license/license.2023.dat.xc")
    sim_env.setdefault("CDS_LIC_ONLY", "1")
    sim_env.setdefault("CDS_AUTO_64BIT", "ALL")
    proc = subprocess.run(cmd, cwd=sim_dir, env=sim_env, stdout=subprocess.PIPE,
                          stderr=subprocess.STDOUT, text=True, check=False)
    run_log.write_text(proc.stdout, encoding="utf-8")
    if proc.returncode != 0 or not output_csv.exists():
        raise RuntimeError(f"random cone simulation failed ({proc.returncode}); see {run_log}")
    with output_csv.open(newline="", encoding="utf-8") as fd:
        reader = csv.reader(fd)
        sim_header = next(reader, [])
        rows = [[cell.strip().lower() for cell in row] for row in reader]
    if sim_header != header or len(rows) != random_num:
        raise RuntimeError(f"invalid random simulation output; see {output_csv}")
    if any(len(row) != len(header) or any(not re.fullmatch(r"[01]+", cell) for cell in row)
           for row in rows):
        raise RuntimeError(f"random simulation produced invalid or unknown values; see {output_csv}")
    return rows, {"random_requested": random_num, "random_generated": len(rows),
                  "input_width": input_width, "input_space_size": input_space,
                  "random_sim_log": str(run_log)}


def run_cone(tool: Path, env: dict[str, str], fsdb: Path, cone_dir: Path,
             log_dir: Path, random_num: int, seed: int) -> dict[str, object]:
    header, target, connections = parse_cone(cone_dir)
    cone_log_dir = log_dir / cone_dir.name
    cone_log_dir.mkdir(parents=True, exist_ok=True)
    raw_csv = cone_log_dir / "fsdbreport.raw.csv"
    report_log = cone_log_dir / "fsdbreport.log"
    clock = fsdb_path(target, connections["clk_i"])

    cmd = [str(tool), str(fsdb), "-strobe", f"{clock}==1", "-shiftneg", "1ps", "-s"]
    for name in header:
        cmd += [fsdb_path(target, connections[name]), "-a", name, "-of", "b"]
    cmd += ["-csv", "-o", str(raw_csv), "-nolog"]
    (cone_log_dir / "fsdbreport.args.txt").write_text("\n".join(cmd) + "\n", encoding="utf-8")
    proc = subprocess.run(cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                          text=True, check=False)
    report_log.write_text(proc.stdout, encoding="utf-8")
    if proc.returncode != 0 or not raw_csv.exists():
        raise RuntimeError(f"fsdbreport failed ({proc.returncode}); see {report_log}")
    if re.search(r"signal not found|not found, abort|read fsdb failed", proc.stdout, re.I):
        raise RuntimeError(f"fsdbreport reported a missing signal; see {report_log}")

    with raw_csv.open(newline="", encoding="utf-8", errors="ignore") as fd:
        rows = list(csv.reader(fd))
    if not rows:
        raise RuntimeError("fsdbreport produced an empty CSV")
    # fsdbreport uses the strobe signal as column zero and aliases thereafter.
    report_header = [item.strip() for item in rows[0]]
    if report_header[1:] != header:
        raise RuntimeError(f"unexpected fsdbreport header: {report_header}")
    clean: list[list[str]] = []
    dropped = 0
    for row in rows[1:]:
        values = [item.strip().lower() for item in row[1:]]
        if len(values) != len(header) or any(not re.fullmatch(r"[01]+", value) for value in values):
            dropped += 1
            continue
        clean.append(values)
    if not clean:
        raise RuntimeError("no clean binary IO samples were extracted")

    outputs = cone_outputs(cone_dir, header)
    fsdb_rows = list(clean)
    random_rows, random_stats = simulate_random_inputs(
        cone_dir, header, outputs, fsdb_rows, random_num, seed, log_dir
    )
    clean.extend(random_rows)
    output_indices = [header.index(name) for name in outputs]
    input_indices = [idx for idx, name in enumerate(header) if name not in outputs]
    observed: dict[tuple[str, ...], tuple[str, ...]] = {}
    conflicts = 0
    for row in clean:
        key = tuple(row[idx] for idx in input_indices)
        value = tuple(row[idx] for idx in output_indices)
        if key in observed and observed[key] != value:
            conflicts += 1
        else:
            observed[key] = value
    if conflicts:
        raise RuntimeError(f"found {conflicts} conflicting input rows")

    output = cone_dir / "io_dump" / f"{cone_dir.name}.io_samples.csv"
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", newline="", encoding="utf-8",
                                     dir=output.parent, delete=False) as fd:
        writer = csv.writer(fd, lineterminator="\n")
        writer.writerow(header)
        writer.writerows(clean)
        temp_path = Path(fd.name)
    temp_path.replace(output)
    fsdb_unique = len({tuple(row[idx] for idx in input_indices) for row in fsdb_rows})
    return {"cone": cone_dir.name, "status": "success", "rows": len(clean),
            "fsdb_rows": len(fsdb_rows), "fsdb_unique_inputs": fsdb_unique,
            "merged_rows": len(clean), "merged_unique_inputs": len(observed),
            "dropped_rows": dropped, "unique_inputs": len(observed), "conflicts": conflicts,
            "output": str(output), "log": str(report_log), **random_stats}


def main() -> int:
    args = parse_args()
    if args.random_num < 0:
        raise SystemExit("ERROR: --random-num must be non-negative")
    seed = args.seed if args.seed is not None else time.time_ns() & ((1 << 63) - 1)
    fsdb = args.fsdb.resolve()
    proj = args.proj.resolve()
    if not fsdb.is_file():
        raise SystemExit(f"ERROR: FSDB not found: {fsdb}")
    cones = sorted(path for path in (proj / "cones").glob("*/*") if path.is_dir())
    if not cones:
        raise SystemExit(f"ERROR: no cones found under {proj}")
    tool = args.verdi_home / "platform/linux64/bin/fsdbreport"
    if not tool.exists():
        raise SystemExit(f"ERROR: fsdbreport not found: {tool}")
    env = os.environ.copy()
    env["VERDI_HOME"] = str(args.verdi_home)
    ugo = args.verdi_home / "share/ugo/linux64/bin/ugo_dist/ugo"
    env["LD_LIBRARY_PATH"] = str(ugo)
    log_dir = proj / "logs" / "gen_io"
    log_dir.mkdir(parents=True, exist_ok=True)

    results: list[dict[str, object]] = []
    failed = False
    for cone in cones:
        try:
            result = run_cone(tool, env, fsdb, cone, log_dir, args.random_num, seed)
            print(f"[PASS] {cone.name}: fsdb_rows={result['fsdb_rows']} "
                  f"random_rows={result['random_generated']} merged_rows={result['merged_rows']} "
                  f"unique_inputs={result['merged_unique_inputs']}")
        except Exception as exc:
            failed = True
            result = {"cone": cone.name, "status": "failed", "error": str(exc)}
            print(f"[FAIL] {cone.name}: {exc}")
        results.append(result)
    summary = {"fsdb": str(fsdb), "project": str(proj), "seed": seed,
               "random_num": args.random_num, "cones": results}
    (log_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(f"Summary: {log_dir / 'summary.json'}")
    print(f"Random seed: {seed}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
