#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path

from _gen_io import DEFAULT_VERDI_HOME, cone_outputs, fsdb_path, parse_cone


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate unreachable assertions for cone inputs unseen in an FSDB"
    )
    parser.add_argument("--proj", type=Path, required=True)
    parser.add_argument("--cone", required=True)
    parser.add_argument("--fsdb", type=Path, required=True)
    parser.add_argument("--verdi-home", type=Path,
                        default=Path(os.environ.get("VERDI_HOME", DEFAULT_VERDI_HOME)))
    return parser.parse_args()


def sanitize(value: str) -> str:
    result = re.sub(r"[^A-Za-z0-9_]", "_", value)
    return result if result and not result[0].isdigit() else f"n_{result}"


def find_cone(proj: Path, cone_name: str) -> Path:
    matches = sorted(path for path in (proj / "cones").glob(f"*/{cone_name}") if path.is_dir())
    if not matches:
        raise RuntimeError(f"cone not found under {proj}: {cone_name}")
    if len(matches) != 1:
        raise RuntimeError(f"cone name is ambiguous under {proj}: {cone_name}")
    return matches[0]


def formal_bind_module(cone_dir: Path) -> str:
    spec_path = cone_dir / "cone_spec.resolved.json"
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    module = str(spec.get("cone", {}).get("module", "")).strip()
    if not module:
        module = str(spec.get("rtl", {}).get("top_module", "")).strip()
    if not module:
        raise RuntimeError(f"cannot determine formal bind module from {spec_path}")
    return module


def extract_seen_inputs(tool: Path, env: dict[str, str], fsdb: Path, cone_dir: Path,
                        inputs: list[str], target: str, connections: dict[str, str],
                        out_dir: Path) -> tuple[set[str], int, int]:
    raw_csv = out_dir / "fsdbreport.inputs.raw.csv"
    report_log = out_dir / "fsdbreport.log"
    clock = fsdb_path(target, connections["clk_i"])
    cmd = [str(tool), str(fsdb), "-strobe", f"{clock}==1", "-shiftneg", "1ps", "-s"]
    for name in inputs:
        cmd += [fsdb_path(target, connections[name]), "-a", name, "-of", "b"]
    cmd += ["-csv", "-o", str(raw_csv), "-nolog"]
    (out_dir / "fsdbreport.args.txt").write_text("\n".join(cmd) + "\n", encoding="utf-8")
    proc = subprocess.run(cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                          text=True, check=False)
    report_log.write_text(proc.stdout, encoding="utf-8")
    if proc.returncode != 0 or not raw_csv.exists():
        raise RuntimeError(f"fsdbreport failed ({proc.returncode}); see {report_log}")
    if re.search(r"signal not found|not found, abort|read fsdb failed", proc.stdout, re.I):
        raise RuntimeError(f"fsdbreport reported a missing signal; see {report_log}")

    with raw_csv.open(newline="", encoding="utf-8", errors="ignore") as fd:
        rows = list(csv.reader(fd))
    if not rows:
        raise RuntimeError("fsdbreport produced an empty CSV")
    report_header = [item.strip() for item in rows[0]]
    if report_header[1:] != inputs:
        raise RuntimeError(f"unexpected fsdbreport header: {report_header}")
    seen: set[str] = set()
    dropped = 0
    for row in rows[1:]:
        values = [item.strip().lower() for item in row[1:]]
        if len(values) != len(inputs) or any(not re.fullmatch(r"[01]+", value) for value in values):
            dropped += 1
            continue
        seen.add("".join(values))
    return seen, max(0, len(rows) - 1), dropped


def render_sv(cone_name: str, bind_module: str, inputs: list[str],
              connections: dict[str, str], unseen: list[int]) -> str:
    safe = sanitize(cone_name)
    module = f"bsdcov_traversal_{safe}"
    width = len(inputs)
    hex_digits = max(1, (width + 3) // 4)
    lines = [
        "// AUTO-GENERATED by BSD-Cov gen_traversal.",
        f"// Cone: {cone_name}",
        f"// Input width: {width}; unseen combinations: {len(unseen)}.",
        f"module {module} (",
        "  input logic clk_i,",
        "  input logic rst_ni,",
    ]
    for idx, name in enumerate(inputs):
        lines.append(f"  input logic {name}" + ("," if idx + 1 < len(inputs) else ""))
    lines += [
        ");",
        "",
        f"  logic [{width - 1}:0] packed_inputs;",
        f"  assign packed_inputs = {{{', '.join(inputs)}}};",
        "",
    ]
    if unseen:
        for value in unseen:
            tag = f"{value:0{hex_digits}x}"
            bits = f"{value:0{width}b}"
            lines += [
                f"  AST_BSDCOV_TRAVERSAL_{safe}_{tag}: assert property (",
                "    @(posedge clk_i) disable iff (!rst_ni)",
                f"      !(packed_inputs == {width}'b{bits})",
                "  );",
                "",
            ]
    else:
        lines += ["  // All input combinations were observed in the FSDB.", ""]
    lines += ["endmodule", "", f"bind {bind_module} {module} u_{module} (",
              f"  .clk_i({connections['clk_i']}),", f"  .rst_ni({connections['rst_ni']}),"]
    for idx, name in enumerate(inputs):
        lines.append(f"  .{name}({connections[name]})" + ("," if idx + 1 < len(inputs) else ""))
    lines += [");", ""]
    return "\n".join(lines)


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent,
                                     delete=False) as fd:
        fd.write(text)
        temp = Path(fd.name)
    temp.replace(path)


def main() -> int:
    args = parse_args()
    proj = args.proj.resolve()
    fsdb = args.fsdb.resolve()
    if not fsdb.is_file():
        raise SystemExit(f"ERROR: FSDB not found: {fsdb}")
    try:
        cone_dir = find_cone(proj, args.cone)
        header, fsdb_target, connections = parse_cone(cone_dir)
        bind_module = formal_bind_module(cone_dir)
        outputs = cone_outputs(cone_dir, header)
        inputs = [name for name in header if name not in outputs]
        input_width = len(inputs)
        if input_width > 10:
            raise RuntimeError(
                f"cannot generate traversal for {args.cone}: input width {input_width} exceeds 10"
            )
        if input_width == 0:
            raise RuntimeError(f"cannot generate traversal for {args.cone}: cone has no inputs")

        tool = args.verdi_home / "platform/linux64/bin/fsdbreport"
        if not tool.exists():
            raise RuntimeError(f"fsdbreport not found: {tool}")
        env = os.environ.copy()
        env["VERDI_HOME"] = str(args.verdi_home)
        env["LD_LIBRARY_PATH"] = str(args.verdi_home / "share/ugo/linux64/bin/ugo_dist/ugo")

        out_dir = proj / "results" / "traversal" / args.cone
        out_dir.mkdir(parents=True, exist_ok=True)
        seen_bits, fsdb_rows, dropped = extract_seen_inputs(
            tool, env, fsdb, cone_dir, inputs, fsdb_target, connections, out_dir
        )
        seen_values = {int(bits, 2) for bits in seen_bits}
        total = 1 << input_width
        unseen = [value for value in range(total) if value not in seen_values]
        sv = out_dir / f"{args.cone}.traversal.assertions.sv"
        filelist = out_dir / f"{args.cone}.traversal.f"
        atomic_write(sv, render_sv(args.cone, bind_module, inputs, connections, unseen))
        atomic_write(filelist, str(sv.resolve()) + "\n")
        summary = {
            "cone": args.cone,
            "cone_dir": str(cone_dir),
            "fsdb": str(fsdb),
            "fsdb_source_hierarchy": fsdb_target,
            "formal_bind_module": bind_module,
            "input_names": inputs,
            "input_width": input_width,
            "total_combinations": total,
            "fsdb_rows": fsdb_rows,
            "dropped_fsdb_rows": dropped,
            "fsdb_unique_combinations": len(seen_values),
            "skipped_combinations": len(seen_values),
            "generated_assertions": len(unseen),
            "assertions_sv": str(sv),
            "filelist": str(filelist),
        }
        atomic_write(out_dir / "summary.json", json.dumps(summary, indent=2) + "\n")
        print(f"Cone: {args.cone}")
        print(f"Input width: {input_width}")
        print(f"FSDB unique combinations: {len(seen_values)}")
        print(f"Generated assertions: {len(unseen)}")
        print(f"SystemVerilog: {sv}")
        print(f"Filelist: {filelist}")
        return 0
    except Exception as exc:
        print(f"ERROR: {exc}", file=os.sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
