// AUTO-GENERATED by BSD-Cov regionasserts.
// Target: targets/ibex/hazard_stall.yaml
// Regions: exp/ibex_bsdcov/hazard_stall_baseline10k/artifacts/regions/regions.json
// Do not edit manually.

bind ibex_id_stage :
  core_ibex_tb_top.dut.u_ibex_top.u_ibex_core.id_stage_i
  bsd_cov_ibex_hazard_stall_region_asserts_bind
  bsd_cov_ibex_hazard_stall_region_asserts_bind_inst (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .branch_decision_i(branch_decision_i),
    .branch_in_dec(branch_in_dec),
    .controller_run(controller_run),
    .data_ind_timing_i(data_ind_timing_i),
    .div_en_dec(div_en_dec),
    .ex_valid_i(ex_valid_i),
    .id_fsm_q(id_fsm_q),
    .instr_fetch_err_i(instr_fetch_err_i),
    .instr_valid_i(instr_valid_i),
    .jump_in_dec(jump_in_dec),
    .lsu_req_dec(lsu_req_dec),
    .lsu_req_done_i(lsu_req_done_i),
    .lsu_resp_valid_i(lsu_resp_valid_i),
    .mult_en_dec(mult_en_dec),
    .outstanding_load_wb_i(outstanding_load_wb_i),
    .outstanding_store_wb_i(outstanding_store_wb_i),
    .ready_wb_i(ready_wb_i),
    .rf_raddr_a_o(rf_raddr_a_o),
    .rf_raddr_b_o(rf_raddr_b_o),
    .rf_ren_a(rf_ren_a),
    .rf_ren_b(rf_ren_b),
    .rf_waddr_wb_i(rf_waddr_wb_i),
    .stall_mem(stall_mem),
    .stall_ld_hz(stall_ld_hz),
    .stall_multdiv(stall_multdiv),
    .stall_branch(stall_branch),
    .stall_jump(stall_jump),
    .rf_rd_wb_hz(fcov_rf_rd_wb_hz)
  );

module bsd_cov_ibex_hazard_stall_region_asserts_bind (clk_i, rst_ni, branch_decision_i, branch_in_dec, controller_run, data_ind_timing_i, div_en_dec, ex_valid_i, id_fsm_q, instr_fetch_err_i, instr_valid_i, jump_in_dec, lsu_req_dec, lsu_req_done_i, lsu_resp_valid_i, mult_en_dec, outstanding_load_wb_i, outstanding_store_wb_i, ready_wb_i, rf_raddr_a_o, rf_raddr_b_o, rf_ren_a, rf_ren_b, rf_waddr_wb_i, stall_mem, stall_ld_hz, stall_multdiv, stall_branch, stall_jump, rf_rd_wb_hz);
  input logic clk_i;
  input logic rst_ni;
  input logic branch_decision_i;
  input logic branch_in_dec;
  input logic controller_run;
  input logic data_ind_timing_i;
  input logic div_en_dec;
  input logic ex_valid_i;
  input logic id_fsm_q;
  input logic instr_fetch_err_i;
  input logic instr_valid_i;
  input logic jump_in_dec;
  input logic lsu_req_dec;
  input logic lsu_req_done_i;
  input logic lsu_resp_valid_i;
  input logic mult_en_dec;
  input logic outstanding_load_wb_i;
  input logic outstanding_store_wb_i;
  input logic ready_wb_i;
  input logic [4:0] rf_raddr_a_o;
  input logic [4:0] rf_raddr_b_o;
  input logic rf_ren_a;
  input logic rf_ren_b;
  input logic [4:0] rf_waddr_wb_i;
  input logic stall_mem;
  input logic stall_ld_hz;
  input logic stall_multdiv;
  input logic stall_branch;
  input logic stall_jump;
  input logic rf_rd_wb_hz;

  /* BSD-Cov region: R_stall_mem_000
   * focus_outputs: stall_mem
   * predicates: [{"field": "lsu_req_dec", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_mem_000;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((lsu_req_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)))) |-> (stall_mem);
  endproperty

  AST_BSDCOV_R_stall_mem_000: assert property (p_BSDCOV_R_stall_mem_000)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_mem_000");
    $assertoff(0, AST_BSDCOV_R_stall_mem_000);
  end

  COV_BSDCOV_R_stall_mem_000: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((lsu_req_dec == 1'b1)) && ((lsu_req_done_i == 1'b0))) && (stall_mem)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_mem_000);
  end

  /* BSD-Cov region: R_stall_mem_001
   * focus_outputs: stall_mem
   * predicates: [{"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"field": "lsu_resp_valid_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_mem_001;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((outstanding_load_wb_i == 1'b1)) && ((lsu_resp_valid_i == 1'b0)))) |-> (stall_mem);
  endproperty

  AST_BSDCOV_R_stall_mem_001: assert property (p_BSDCOV_R_stall_mem_001)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_mem_001");
    $assertoff(0, AST_BSDCOV_R_stall_mem_001);
  end

  COV_BSDCOV_R_stall_mem_001: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((outstanding_load_wb_i == 1'b1)) && ((lsu_resp_valid_i == 1'b0))) && (stall_mem)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_mem_001);
  end

  /* BSD-Cov region: R_stall_mem_002
   * focus_outputs: stall_mem
   * predicates: [{"field": "outstanding_store_wb_i", "type": "eq", "value": 1}, {"field": "lsu_resp_valid_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_mem_002;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((outstanding_store_wb_i == 1'b1)) && ((lsu_resp_valid_i == 1'b0)))) |-> (stall_mem);
  endproperty

  AST_BSDCOV_R_stall_mem_002: assert property (p_BSDCOV_R_stall_mem_002)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_mem_002");
    $assertoff(0, AST_BSDCOV_R_stall_mem_002);
  end

  COV_BSDCOV_R_stall_mem_002: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((outstanding_store_wb_i == 1'b1)) && ((lsu_resp_valid_i == 1'b0))) && (stall_mem)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_mem_002);
  end

  /* BSD-Cov region: R_stall_ld_hz_001
   * focus_outputs: stall_ld_hz
   * predicates: [{"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"field": "rf_ren_a", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_stall_ld_hz_001;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((outstanding_load_wb_i == 1'b1)) && ((rf_ren_a == 1'b1)))) |-> (stall_ld_hz);
  endproperty

  AST_BSDCOV_R_stall_ld_hz_001: assert property (p_BSDCOV_R_stall_ld_hz_001)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_ld_hz_001");
    $assertoff(0, AST_BSDCOV_R_stall_ld_hz_001);
  end

  COV_BSDCOV_R_stall_ld_hz_001: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((outstanding_load_wb_i == 1'b1)) && ((rf_ren_a == 1'b1))) && (stall_ld_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_ld_hz_001);
  end

  /* BSD-Cov region: R_stall_ld_hz_000
   * focus_outputs: stall_ld_hz
   * predicates: [{"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}]
   */
  property p_BSDCOV_R_stall_ld_hz_000;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((outstanding_load_wb_i == 1'b1)) && ((rf_raddr_b_o == rf_waddr_wb_i)))) |-> (stall_ld_hz);
  endproperty

  AST_BSDCOV_R_stall_ld_hz_000: assert property (p_BSDCOV_R_stall_ld_hz_000)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_ld_hz_000");
    $assertoff(0, AST_BSDCOV_R_stall_ld_hz_000);
  end

  COV_BSDCOV_R_stall_ld_hz_000: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((outstanding_load_wb_i == 1'b1)) && ((rf_raddr_b_o == rf_waddr_wb_i))) && (stall_ld_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_ld_hz_000);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_001
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "rf_ren_a", "type": "eq", "value": 0}, {"field": "rf_ren_b", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_001;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b0)) && ((rf_ren_b == 1'b1)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_001: assert property (p_BSDCOV_R_rf_rd_wb_hz_001)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_001");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_001);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_001: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b0)) && ((rf_ren_b == 1'b1))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_001);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_000
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "rf_ren_a", "type": "eq", "value": 1}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "lsu_resp_valid_i", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_000;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b1)) && ((id_fsm_q == 1'b1)) && ((lsu_resp_valid_i == 1'b1)) && ((controller_run == 1'b1)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_000: assert property (p_BSDCOV_R_rf_rd_wb_hz_000)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_000");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_000);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_000: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b1)) && ((id_fsm_q == 1'b1)) && ((lsu_resp_valid_i == 1'b1)) && ((controller_run == 1'b1))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_000);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_002
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "rf_ren_a", "type": "eq", "value": 1}, {"field": "data_ind_timing_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}, {"field": "rf_ren_b", "type": "eq", "value": 0}, {"field": "branch_in_dec", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_002;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b1)) && ((data_ind_timing_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((rf_ren_b == 1'b0)) && ((branch_in_dec == 1'b1)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_002: assert property (p_BSDCOV_R_rf_rd_wb_hz_002)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_002");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_002);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_002: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b1)) && ((data_ind_timing_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((rf_ren_b == 1'b0)) && ((branch_in_dec == 1'b1))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_002);
  end

  /* BSD-Cov region: R_stall_jump_001
   * focus_outputs: stall_jump
   * predicates: [{"field": "jump_in_dec", "type": "eq", "value": 1}, {"field": "ready_wb_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_jump_001;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((jump_in_dec == 1'b1)) && ((ready_wb_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((id_fsm_q == 1'b1)) && ((controller_run == 1'b1)) && ((instr_fetch_err_i == 1'b0)))) |-> (stall_jump);
  endproperty

  AST_BSDCOV_R_stall_jump_001: assert property (p_BSDCOV_R_stall_jump_001)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_jump_001");
    $assertoff(0, AST_BSDCOV_R_stall_jump_001);
  end

  COV_BSDCOV_R_stall_jump_001: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((jump_in_dec == 1'b1)) && ((ready_wb_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((id_fsm_q == 1'b1)) && ((controller_run == 1'b1)) && ((instr_fetch_err_i == 1'b0))) && (stall_jump)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_jump_001);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_007
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "rf_ren_a", "type": "eq", "value": 1}, {"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"field": "ready_wb_i", "type": "eq", "value": 0}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "div_en_dec", "type": "eq", "value": 0}, {"field": "jump_in_dec", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_007;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b1)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((ready_wb_i == 1'b0)) && ((id_fsm_q == 1'b1)) && ((div_en_dec == 1'b0)) && ((jump_in_dec == 1'b1)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_007: assert property (p_BSDCOV_R_rf_rd_wb_hz_007)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_007");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_007);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_007: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b1)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((ready_wb_i == 1'b0)) && ((id_fsm_q == 1'b1)) && ((div_en_dec == 1'b0)) && ((jump_in_dec == 1'b1))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_007);
  end

  /* BSD-Cov region: R_stall_multdiv_001
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "lsu_req_dec", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_multdiv_001;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((mult_en_dec == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((lsu_req_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_001: assert property (p_BSDCOV_R_stall_multdiv_001)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_001");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_001);
  end

  COV_BSDCOV_R_stall_multdiv_001: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((mult_en_dec == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((lsu_req_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_001);
  end

  /* BSD-Cov region: R_stall_jump_000
   * focus_outputs: stall_jump
   * predicates: [{"field": "jump_in_dec", "type": "eq", "value": 1}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_jump_000;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((jump_in_dec == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)))) |-> (stall_jump);
  endproperty

  AST_BSDCOV_R_stall_jump_000: assert property (p_BSDCOV_R_stall_jump_000)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_jump_000");
    $assertoff(0, AST_BSDCOV_R_stall_jump_000);
  end

  COV_BSDCOV_R_stall_jump_000: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((jump_in_dec == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0))) && (stall_jump)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_jump_000);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_005
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "rf_waddr_wb_i", "type": "neq", "value": 0}, {"field": "rf_ren_a", "type": "eq", "value": 1}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"field": "branch_in_dec", "type": "eq", "value": 0}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "data_ind_timing_i", "type": "eq", "value": 1}, {"field": "ex_valid_i", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_005;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_waddr_wb_i != 5'd0)) && ((rf_ren_a == 1'b1)) && ((outstanding_load_wb_i == 1'b1)) && ((controller_run == 1'b1)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((branch_in_dec == 1'b0)) && ((instr_fetch_err_i == 1'b0)) && ((data_ind_timing_i == 1'b1)) && ((ex_valid_i == 1'b1)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_005: assert property (p_BSDCOV_R_rf_rd_wb_hz_005)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_005");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_005);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_005: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_waddr_wb_i != 5'd0)) && ((rf_ren_a == 1'b1)) && ((outstanding_load_wb_i == 1'b1)) && ((controller_run == 1'b1)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((branch_in_dec == 1'b0)) && ((instr_fetch_err_i == 1'b0)) && ((data_ind_timing_i == 1'b1)) && ((ex_valid_i == 1'b1))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_005);
  end

  /* BSD-Cov region: R_stall_multdiv_005
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"field": "ready_wb_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_multdiv_005;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((instr_fetch_err_i == 1'b0)) && ((mult_en_dec == 1'b1)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((ready_wb_i == 1'b0)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_005: assert property (p_BSDCOV_R_stall_multdiv_005)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_005");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_005);
  end

  COV_BSDCOV_R_stall_multdiv_005: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((instr_fetch_err_i == 1'b0)) && ((mult_en_dec == 1'b1)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((ready_wb_i == 1'b0))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_005);
  end

  /* BSD-Cov region: R_stall_jump_002
   * focus_outputs: stall_jump
   * predicates: [{"field": "jump_in_dec", "type": "eq", "value": 1}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "ready_wb_i", "type": "eq", "value": 0}, {"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}]
   */
  property p_BSDCOV_R_stall_jump_002;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((jump_in_dec == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((ready_wb_i == 1'b0)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((rf_raddr_b_o != rf_waddr_wb_i)))) |-> (stall_jump);
  endproperty

  AST_BSDCOV_R_stall_jump_002: assert property (p_BSDCOV_R_stall_jump_002)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_jump_002");
    $assertoff(0, AST_BSDCOV_R_stall_jump_002);
  end

  COV_BSDCOV_R_stall_jump_002: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((jump_in_dec == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((ready_wb_i == 1'b0)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((rf_raddr_b_o != rf_waddr_wb_i))) && (stall_jump)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_jump_002);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_004
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "rf_ren_a", "type": "eq", "value": 1}, {"field": "lsu_req_dec", "type": "eq", "value": 1}, {"field": "rf_ren_b", "type": "eq", "value": 0}, {"field": "branch_decision_i", "type": "eq", "value": 1}, {"field": "lsu_resp_valid_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "controller_run", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_004;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b1)) && ((lsu_req_dec == 1'b1)) && ((rf_ren_b == 1'b0)) && ((branch_decision_i == 1'b1)) && ((lsu_resp_valid_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_004: assert property (p_BSDCOV_R_rf_rd_wb_hz_004)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_004");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_004);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_004: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((rf_ren_a == 1'b1)) && ((lsu_req_dec == 1'b1)) && ((rf_ren_b == 1'b0)) && ((branch_decision_i == 1'b1)) && ((lsu_resp_valid_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_004);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_003
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "lsu_req_dec", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}, {"field": "data_ind_timing_i", "type": "eq", "value": 0}, {"field": "id_fsm_q", "type": "eq", "value": 0}, {"field": "rf_ren_b", "type": "eq", "value": 1}, {"field": "ready_wb_i", "type": "eq", "value": 0}, {"field": "lsu_resp_valid_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_003;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((lsu_req_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((data_ind_timing_i == 1'b0)) && ((id_fsm_q == 1'b0)) && ((rf_ren_b == 1'b1)) && ((ready_wb_i == 1'b0)) && ((lsu_resp_valid_i == 1'b0)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_003: assert property (p_BSDCOV_R_rf_rd_wb_hz_003)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_003");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_003);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_003: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((lsu_req_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((data_ind_timing_i == 1'b0)) && ((id_fsm_q == 1'b0)) && ((rf_ren_b == 1'b1)) && ((ready_wb_i == 1'b0)) && ((lsu_resp_valid_i == 1'b0))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_003);
  end

  /* BSD-Cov region: R_stall_branch_001
   * focus_outputs: stall_branch
   * predicates: [{"field": "branch_in_dec", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "ready_wb_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_branch_001;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((branch_in_dec == 1'b1)) && ((controller_run == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((id_fsm_q == 1'b1)) && ((ready_wb_i == 1'b0)))) |-> (stall_branch);
  endproperty

  AST_BSDCOV_R_stall_branch_001: assert property (p_BSDCOV_R_stall_branch_001)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_branch_001");
    $assertoff(0, AST_BSDCOV_R_stall_branch_001);
  end

  COV_BSDCOV_R_stall_branch_001: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((branch_in_dec == 1'b1)) && ((controller_run == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((id_fsm_q == 1'b1)) && ((ready_wb_i == 1'b0))) && (stall_branch)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_branch_001);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_006
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "controller_run", "type": "eq", "value": 0}, {"field": "rf_ren_a", "type": "eq", "value": 1}, {"field": "ex_valid_i", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}, {"field": "jump_in_dec", "type": "eq", "value": 0}, {"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_006;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((controller_run == 1'b0)) && ((rf_ren_a == 1'b1)) && ((ex_valid_i == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((jump_in_dec == 1'b0)) && ((rf_raddr_b_o == rf_waddr_wb_i)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_006: assert property (p_BSDCOV_R_rf_rd_wb_hz_006)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_006");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_006);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_006: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_a_o == rf_waddr_wb_i)) && ((controller_run == 1'b0)) && ((rf_ren_a == 1'b1)) && ((ex_valid_i == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((jump_in_dec == 1'b0)) && ((rf_raddr_b_o == rf_waddr_wb_i))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_006);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_011
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "rf_waddr_wb_i", "type": "neq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "jump_in_dec", "type": "eq", "value": 0}, {"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "ex_valid_i", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_011;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((rf_waddr_wb_i != 5'd0)) && ((outstanding_load_wb_i == 1'b1)) && ((mult_en_dec == 1'b1)) && ((jump_in_dec == 1'b0)) && ((rf_raddr_a_o == rf_waddr_wb_i)) && ((ex_valid_i == 1'b1)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_011: assert property (p_BSDCOV_R_rf_rd_wb_hz_011)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_011");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_011);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_011: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((rf_waddr_wb_i != 5'd0)) && ((outstanding_load_wb_i == 1'b1)) && ((mult_en_dec == 1'b1)) && ((jump_in_dec == 1'b0)) && ((rf_raddr_a_o == rf_waddr_wb_i)) && ((ex_valid_i == 1'b1))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_011);
  end

  /* BSD-Cov region: R_stall_multdiv_002
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "ready_wb_i", "type": "eq", "value": 0}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "div_en_dec", "type": "eq", "value": 1}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_multdiv_002;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((ready_wb_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((div_en_dec == 1'b1)) && ((outstanding_load_wb_i == 1'b0)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_002: assert property (p_BSDCOV_R_stall_multdiv_002)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_002");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_002);
  end

  COV_BSDCOV_R_stall_multdiv_002: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((ready_wb_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((div_en_dec == 1'b1)) && ((outstanding_load_wb_i == 1'b0))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_002);
  end

  /* BSD-Cov region: R_stall_multdiv_003
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "ready_wb_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_multdiv_003;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((mult_en_dec == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((ready_wb_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_003: assert property (p_BSDCOV_R_stall_multdiv_003)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_003");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_003);
  end

  COV_BSDCOV_R_stall_multdiv_003: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((mult_en_dec == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((ready_wb_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_003);
  end

  /* BSD-Cov region: R_stall_multdiv_000
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "ex_valid_i", "type": "eq", "value": 0}, {"field": "data_ind_timing_i", "type": "eq", "value": 1}, {"field": "jump_in_dec", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "controller_run", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_stall_multdiv_000;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((mult_en_dec == 1'b1)) && ((ex_valid_i == 1'b0)) && ((data_ind_timing_i == 1'b1)) && ((jump_in_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_000: assert property (p_BSDCOV_R_stall_multdiv_000)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_000");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_000);
  end

  COV_BSDCOV_R_stall_multdiv_000: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((mult_en_dec == 1'b1)) && ((ex_valid_i == 1'b0)) && ((data_ind_timing_i == 1'b1)) && ((jump_in_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_000);
  end

  /* BSD-Cov region: R_stall_branch_000
   * focus_outputs: stall_branch
   * predicates: [{"field": "branch_in_dec", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "rf_ren_b", "type": "eq", "value": 0}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "rf_ren_a", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_branch_000;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((branch_in_dec == 1'b1)) && ((controller_run == 1'b1)) && ((rf_ren_b == 1'b0)) && ((instr_fetch_err_i == 1'b0)) && ((id_fsm_q == 1'b1)) && ((rf_ren_a == 1'b0)))) |-> (stall_branch);
  endproperty

  AST_BSDCOV_R_stall_branch_000: assert property (p_BSDCOV_R_stall_branch_000)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_branch_000");
    $assertoff(0, AST_BSDCOV_R_stall_branch_000);
  end

  COV_BSDCOV_R_stall_branch_000: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((branch_in_dec == 1'b1)) && ((controller_run == 1'b1)) && ((rf_ren_b == 1'b0)) && ((instr_fetch_err_i == 1'b0)) && ((id_fsm_q == 1'b1)) && ((rf_ren_a == 1'b0))) && (stall_branch)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_branch_000);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_009
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"field": "outstanding_store_wb_i", "type": "eq", "value": 1}, {"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "div_en_dec", "type": "eq", "value": 1}, {"field": "branch_decision_i", "type": "eq", "value": 0}, {"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_009;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((outstanding_load_wb_i == 1'b1)) && ((outstanding_store_wb_i == 1'b1)) && ((mult_en_dec == 1'b1)) && ((div_en_dec == 1'b1)) && ((branch_decision_i == 1'b0)) && ((rf_raddr_a_o == rf_waddr_wb_i)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_009: assert property (p_BSDCOV_R_rf_rd_wb_hz_009)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_009");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_009);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_009: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((outstanding_load_wb_i == 1'b1)) && ((outstanding_store_wb_i == 1'b1)) && ((mult_en_dec == 1'b1)) && ((div_en_dec == 1'b1)) && ((branch_decision_i == 1'b0)) && ((rf_raddr_a_o == rf_waddr_wb_i))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_009);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_010
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "outstanding_store_wb_i", "type": "eq", "value": 1}, {"field": "div_en_dec", "type": "eq", "value": 1}, {"field": "data_ind_timing_i", "type": "eq", "value": 0}, {"field": "lsu_req_dec", "type": "eq", "value": 1}, {"field": "ready_wb_i", "type": "eq", "value": 0}, {"field": "branch_decision_i", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_010;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((outstanding_load_wb_i == 1'b1)) && ((controller_run == 1'b1)) && ((mult_en_dec == 1'b1)) && ((outstanding_store_wb_i == 1'b1)) && ((div_en_dec == 1'b1)) && ((data_ind_timing_i == 1'b0)) && ((lsu_req_dec == 1'b1)) && ((ready_wb_i == 1'b0)) && ((branch_decision_i == 1'b1)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_010: assert property (p_BSDCOV_R_rf_rd_wb_hz_010)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_010");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_010);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_010: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((outstanding_load_wb_i == 1'b1)) && ((controller_run == 1'b1)) && ((mult_en_dec == 1'b1)) && ((outstanding_store_wb_i == 1'b1)) && ((div_en_dec == 1'b1)) && ((data_ind_timing_i == 1'b0)) && ((lsu_req_dec == 1'b1)) && ((ready_wb_i == 1'b0)) && ((branch_decision_i == 1'b1))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_010);
  end

  /* BSD-Cov region: R_rf_rd_wb_hz_008
   * focus_outputs: rf_rd_wb_hz
   * predicates: [{"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "eq_field"}, {"field": "rf_ren_b", "type": "eq", "value": 1}, {"field": "lsu_req_dec", "type": "eq", "value": 1}, {"field": "branch_decision_i", "type": "eq", "value": 1}, {"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}, {"field": "mult_en_dec", "type": "eq", "value": 0}, {"field": "outstanding_store_wb_i", "type": "eq", "value": 0}, {"field": "jump_in_dec", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_rf_rd_wb_hz_008;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((rf_ren_b == 1'b1)) && ((lsu_req_dec == 1'b1)) && ((branch_decision_i == 1'b1)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((id_fsm_q == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((mult_en_dec == 1'b0)) && ((outstanding_store_wb_i == 1'b0)) && ((jump_in_dec == 1'b0)))) |-> (rf_rd_wb_hz);
  endproperty

  AST_BSDCOV_R_rf_rd_wb_hz_008: assert property (p_BSDCOV_R_rf_rd_wb_hz_008)
  else begin
    $error("BSD-Cov region assertion failed: R_rf_rd_wb_hz_008");
    $assertoff(0, AST_BSDCOV_R_rf_rd_wb_hz_008);
  end

  COV_BSDCOV_R_rf_rd_wb_hz_008: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((rf_raddr_b_o == rf_waddr_wb_i)) && ((rf_ren_b == 1'b1)) && ((lsu_req_dec == 1'b1)) && ((branch_decision_i == 1'b1)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((id_fsm_q == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((mult_en_dec == 1'b0)) && ((outstanding_store_wb_i == 1'b0)) && ((jump_in_dec == 1'b0))) && (rf_rd_wb_hz)
  ) begin
    $assertoff(0, COV_BSDCOV_R_rf_rd_wb_hz_008);
  end

  /* BSD-Cov region: R_stall_multdiv_006
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "div_en_dec", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"field": "mult_en_dec", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_multdiv_006;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((instr_fetch_err_i == 1'b0)) && ((div_en_dec == 1'b1)) && ((controller_run == 1'b1)) && ((outstanding_load_wb_i == 1'b1)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((id_fsm_q == 1'b1)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((mult_en_dec == 1'b0)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_006: assert property (p_BSDCOV_R_stall_multdiv_006)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_006");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_006);
  end

  COV_BSDCOV_R_stall_multdiv_006: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((instr_fetch_err_i == 1'b0)) && ((div_en_dec == 1'b1)) && ((controller_run == 1'b1)) && ((outstanding_load_wb_i == 1'b1)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((id_fsm_q == 1'b1)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((mult_en_dec == 1'b0))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_006);
  end

  /* BSD-Cov region: R_stall_multdiv_004
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 1}, {"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "id_fsm_q", "type": "eq", "value": 1}, {"field": "rf_ren_b", "type": "eq", "value": 0}, {"field": "rf_ren_a", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_multdiv_004;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((instr_fetch_err_i == 1'b0)) && ((outstanding_load_wb_i == 1'b1)) && ((mult_en_dec == 1'b1)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((rf_ren_b == 1'b0)) && ((rf_ren_a == 1'b0)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_004: assert property (p_BSDCOV_R_stall_multdiv_004)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_004");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_004);
  end

  COV_BSDCOV_R_stall_multdiv_004: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((instr_fetch_err_i == 1'b0)) && ((outstanding_load_wb_i == 1'b1)) && ((mult_en_dec == 1'b1)) && ((controller_run == 1'b1)) && ((id_fsm_q == 1'b1)) && ((rf_ren_b == 1'b0)) && ((rf_ren_a == 1'b0))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_004);
  end

  /* BSD-Cov region: R_stall_jump_003
   * focus_outputs: stall_jump
   * predicates: [{"field": "jump_in_dec", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "mult_en_dec", "type": "eq", "value": 0}, {"field": "div_en_dec", "type": "eq", "value": 0}, {"field": "lsu_req_dec", "type": "eq", "value": 0}, {"field": "id_fsm_q", "type": "eq", "value": 0}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}, {"field": "branch_in_dec", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_jump_003;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((jump_in_dec == 1'b1)) && ((controller_run == 1'b1)) && ((mult_en_dec == 1'b0)) && ((div_en_dec == 1'b0)) && ((lsu_req_dec == 1'b0)) && ((id_fsm_q == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((branch_in_dec == 1'b0)))) |-> (stall_jump);
  endproperty

  AST_BSDCOV_R_stall_jump_003: assert property (p_BSDCOV_R_stall_jump_003)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_jump_003");
    $assertoff(0, AST_BSDCOV_R_stall_jump_003);
  end

  COV_BSDCOV_R_stall_jump_003: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((jump_in_dec == 1'b1)) && ((controller_run == 1'b1)) && ((mult_en_dec == 1'b0)) && ((div_en_dec == 1'b0)) && ((lsu_req_dec == 1'b0)) && ((id_fsm_q == 1'b0)) && ((outstanding_load_wb_i == 1'b0)) && ((branch_in_dec == 1'b0))) && (stall_jump)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_jump_003);
  end

  /* BSD-Cov region: R_stall_multdiv_007
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "div_en_dec", "type": "eq", "value": 1}, {"field": "jump_in_dec", "type": "eq", "value": 1}, {"field": "ready_wb_i", "type": "eq", "value": 1}, {"field": "lsu_req_dec", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}, {"field": "id_fsm_q", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_stall_multdiv_007;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((div_en_dec == 1'b1)) && ((jump_in_dec == 1'b1)) && ((ready_wb_i == 1'b1)) && ((lsu_req_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((id_fsm_q == 1'b1)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_007: assert property (p_BSDCOV_R_stall_multdiv_007)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_007");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_007);
  end

  COV_BSDCOV_R_stall_multdiv_007: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((instr_fetch_err_i == 1'b0)) && ((controller_run == 1'b1)) && ((div_en_dec == 1'b1)) && ((jump_in_dec == 1'b1)) && ((ready_wb_i == 1'b1)) && ((lsu_req_dec == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((id_fsm_q == 1'b1))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_007);
  end

  /* BSD-Cov region: R_stall_branch_002
   * focus_outputs: stall_branch
   * predicates: [{"field": "branch_in_dec", "type": "eq", "value": 1}, {"field": "controller_run", "type": "eq", "value": 1}, {"field": "instr_fetch_err_i", "type": "eq", "value": 0}, {"field": "jump_in_dec", "type": "eq", "value": 1}, {"field": "ready_wb_i", "type": "eq", "value": 1}, {"field": "lsu_req_done_i", "type": "eq", "value": 0}, {"field": "id_fsm_q", "type": "eq", "value": 1}]
   */
  property p_BSDCOV_R_stall_branch_002;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((branch_in_dec == 1'b1)) && ((controller_run == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((jump_in_dec == 1'b1)) && ((ready_wb_i == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((id_fsm_q == 1'b1)))) |-> (stall_branch);
  endproperty

  AST_BSDCOV_R_stall_branch_002: assert property (p_BSDCOV_R_stall_branch_002)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_branch_002");
    $assertoff(0, AST_BSDCOV_R_stall_branch_002);
  end

  COV_BSDCOV_R_stall_branch_002: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((branch_in_dec == 1'b1)) && ((controller_run == 1'b1)) && ((instr_fetch_err_i == 1'b0)) && ((jump_in_dec == 1'b1)) && ((ready_wb_i == 1'b1)) && ((lsu_req_done_i == 1'b0)) && ((id_fsm_q == 1'b1))) && (stall_branch)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_branch_002);
  end

  /* BSD-Cov region: R_stall_multdiv_008
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "controller_run", "type": "eq", "value": 1}, {"field": "ex_valid_i", "type": "eq", "value": 0}, {"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "lsu_req_dec", "type": "eq", "value": 0}, {"field": "outstanding_store_wb_i", "type": "eq", "value": 1}, {"field": "outstanding_load_wb_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_multdiv_008;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((controller_run == 1'b1)) && ((ex_valid_i == 1'b0)) && ((mult_en_dec == 1'b1)) && ((lsu_req_dec == 1'b0)) && ((outstanding_store_wb_i == 1'b1)) && ((outstanding_load_wb_i == 1'b0)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_008: assert property (p_BSDCOV_R_stall_multdiv_008)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_008");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_008);
  end

  COV_BSDCOV_R_stall_multdiv_008: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((controller_run == 1'b1)) && ((ex_valid_i == 1'b0)) && ((mult_en_dec == 1'b1)) && ((lsu_req_dec == 1'b0)) && ((outstanding_store_wb_i == 1'b1)) && ((outstanding_load_wb_i == 1'b0))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_008);
  end

  /* BSD-Cov region: R_stall_multdiv_009
   * focus_outputs: stall_multdiv
   * predicates: [{"field": "controller_run", "type": "eq", "value": 1}, {"field": "ex_valid_i", "type": "eq", "value": 0}, {"field": "mult_en_dec", "type": "eq", "value": 1}, {"field": "lsu_req_dec", "type": "eq", "value": 0}, {"field": "div_en_dec", "type": "eq", "value": 1}, {"lhs": "rf_raddr_a_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"lhs": "rf_raddr_b_o", "rhs": "rf_waddr_wb_i", "type": "neq_field"}, {"field": "ready_wb_i", "type": "eq", "value": 0}]
   */
  property p_BSDCOV_R_stall_multdiv_009;
    @(posedge clk_i) disable iff (!rst_ni)
      (instr_valid_i && (((controller_run == 1'b1)) && ((ex_valid_i == 1'b0)) && ((mult_en_dec == 1'b1)) && ((lsu_req_dec == 1'b0)) && ((div_en_dec == 1'b1)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((ready_wb_i == 1'b0)))) |-> (stall_multdiv);
  endproperty

  AST_BSDCOV_R_stall_multdiv_009: assert property (p_BSDCOV_R_stall_multdiv_009)
  else begin
    $error("BSD-Cov region assertion failed: R_stall_multdiv_009");
    $assertoff(0, AST_BSDCOV_R_stall_multdiv_009);
  end

  COV_BSDCOV_R_stall_multdiv_009: cover property (
    @(posedge clk_i) disable iff (!rst_ni)
      instr_valid_i && (((controller_run == 1'b1)) && ((ex_valid_i == 1'b0)) && ((mult_en_dec == 1'b1)) && ((lsu_req_dec == 1'b0)) && ((div_en_dec == 1'b1)) && ((rf_raddr_a_o != rf_waddr_wb_i)) && ((rf_raddr_b_o != rf_waddr_wb_i)) && ((ready_wb_i == 1'b0))) && (stall_multdiv)
  ) begin
    $assertoff(0, COV_BSDCOV_R_stall_multdiv_009);
  end

endmodule
