// AUTO-GENERATED by BSD-Cov verific_conegen.
// Target module: ibex_id_stage
// Source spec: /home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/module_bind/stall_mem-stall_ld_hz-stall_multdiv-stall_branch-stall_jump-1111/cone_spec.resolved.json
// Do not edit manually.

module bsdcov_cone_stall_mem_stall_ld_hz_stall_multdiv_stall_branch_stall_jump_1111 (
  input  logic branch_in_dec,
  input  logic branch_not_set,
  input  logic controller_run,
  input  logic csr_mstatus_tw_i,
  input  logic data_ind_timing_i,
  input  logic debug_mode_o,
  input  logic div_en_dec,
  input  logic dret_insn_dec,
  input  logic ex_valid_i,
  input  logic id_fsm_q,
  input  logic illegal_csr_insn_i,
  input  logic illegal_insn_dec,
  input  logic instr_fetch_err_i,
  input  logic instr_valid_i,
  input  logic jump_in_dec,
  input  logic lsu_req_dec,
  input  logic lsu_req_done_i,
  input  logic lsu_resp_valid_i,
  input  logic mret_insn_dec,
  input  logic mult_en_dec,
  input  logic outstanding_load_wb_i,
  input  logic outstanding_store_wb_i,
  input  logic [1:0] priv_mode_i_0_,
  input  logic [1:0] priv_mode_i_1_,
  input  logic ready_wb_i,
  input  logic [4:0] rf_raddr_a_o_0_,
  input  logic [4:0] rf_raddr_a_o_1_,
  input  logic [4:0] rf_raddr_a_o_2_,
  input  logic [4:0] rf_raddr_a_o_3_,
  input  logic [4:0] rf_raddr_a_o_4_,
  input  logic [4:0] rf_raddr_b_o_0_,
  input  logic [4:0] rf_raddr_b_o_1_,
  input  logic [4:0] rf_raddr_b_o_2_,
  input  logic [4:0] rf_raddr_b_o_3_,
  input  logic [4:0] rf_raddr_b_o_4_,
  input  logic rf_ren_a_dec,
  input  logic rf_ren_b_dec,
  input  logic [4:0] rf_waddr_wb_i_0_,
  input  logic [4:0] rf_waddr_wb_i_1_,
  input  logic [4:0] rf_waddr_wb_i_2_,
  input  logic [4:0] rf_waddr_wb_i_3_,
  input  logic [4:0] rf_waddr_wb_i_4_,
  input  logic wfi_insn_dec,
  output logic stall_mem,
  output logic stall_ld_hz,
  output logic stall_multdiv,
  output logic stall_branch,
  output logic stall_jump
);

  logic [1:0] n_ibex_id_stage_instr_type_wb_o_1_;
  logic n_ibex_id_stage_gen_stall_mem_outstanding_memory_access;
  logic n_ibex_id_stage_gen_stall_mem_rf_rd_a_hz;
  logic n_ibex_id_stage_gen_stall_mem_rf_rd_a_wb_match;
  logic n_ibex_id_stage_gen_stall_mem_rf_rd_b_hz;
  logic n_ibex_id_stage_gen_stall_mem_rf_rd_b_wb_match;
  logic n_ibex_id_stage_illegal_dret_insn;
  logic n_ibex_id_stage_illegal_insn_o;
  logic n_ibex_id_stage_illegal_umode_insn;
  logic n_ibex_id_stage_instr_executing_spec;
  logic n_ibex_id_stage_multdiv_en_dec;
  logic n_ibex_id_stage_multicycle_done;
  logic n_ibex_id_stage_n1058;
  logic n_ibex_id_stage_n4;
  logic n_ibex_id_stage_n5;
  logic n_ibex_id_stage_n6;
  logic n_ibex_id_stage_n763;
  logic n_ibex_id_stage_n765;
  logic n_ibex_id_stage_n766;
  logic n_ibex_id_stage_n767;
  logic n_ibex_id_stage_n768;
  logic n_ibex_id_stage_n769;
  logic n_ibex_id_stage_n771;
  logic n_ibex_id_stage_n772;
  logic n_ibex_id_stage_n773;
  logic n_ibex_id_stage_n7;
  logic n_ibex_id_stage_n883;
  logic n_ibex_id_stage_n893;
  logic n_ibex_id_stage_n894;
  logic n_ibex_id_stage_n895;
  logic n_ibex_id_stage_n896;
  logic n_ibex_id_stage_n909;
  logic n_ibex_id_stage_n910;
  logic n_ibex_id_stage_n915;
  logic n_ibex_id_stage_n917;
  logic n_ibex_id_stage_n918;
  logic n_ibex_id_stage_n919;
  logic n_ibex_id_stage_n922;
  logic n_ibex_id_stage_n923;
  logic n_ibex_id_stage_n924;
  logic n_ibex_id_stage_n949;
  logic n_ibex_id_stage_n951;
  logic n_ibex_id_stage_n952;
  logic n_ibex_id_stage_n961;
  logic n_ibex_id_stage_n962;
  logic n_ibex_id_stage_n970;
  logic n_ibex_id_stage_n971;
  logic n_ibex_id_stage_n972;
  logic n_ibex_id_stage_n974;
  logic n_ibex_id_stage_n975;
  logic n_ibex_id_stage_n976;
  logic n_ibex_id_stage_n977;
  logic n_ibex_id_stage_n978;
  logic n_ibex_id_stage_n979;
  logic n_ibex_id_stage_n980;
  logic n_ibex_id_stage_n982;
  logic n_ibex_id_stage_n983;
  logic n_ibex_id_stage_n984;
  logic n_ibex_id_stage_n985;
  logic n_ibex_id_stage_n986;
  logic n_ibex_id_stage_n987;
  logic n_ibex_id_stage_n988;
  logic n_ibex_id_stage_rf_ren_a;
  logic n_ibex_id_stage_rf_ren_b;
  logic n_ibex_id_stage_stall_branch;
  logic n_ibex_id_stage_stall_jump;
  logic n_ibex_id_stage_stall_ld_hz;
  logic n_ibex_id_stage_stall_mem;
  logic n_ibex_id_stage_stall_multdiv;

  VERIFIC_AND u_i615 (
    .a0(n_ibex_id_stage_n951),
    .a1(n_ibex_id_stage_n952),
    .o(n_ibex_id_stage_gen_stall_mem_outstanding_memory_access)
  );

  VERIFIC_AND u_i652 (
    .a0(n_ibex_id_stage_gen_stall_mem_rf_rd_a_wb_match),
    .a1(n_ibex_id_stage_rf_ren_a),
    .o(n_ibex_id_stage_gen_stall_mem_rf_rd_a_hz)
  );

  VERIFIC_AND u_i643 (
    .a0(n_ibex_id_stage_n979),
    .a1(n_ibex_id_stage_n980),
    .o(n_ibex_id_stage_gen_stall_mem_rf_rd_a_wb_match)
  );

  VERIFIC_AND u_i653 (
    .a0(n_ibex_id_stage_gen_stall_mem_rf_rd_b_wb_match),
    .a1(n_ibex_id_stage_rf_ren_b),
    .o(n_ibex_id_stage_gen_stall_mem_rf_rd_b_hz)
  );

  VERIFIC_AND u_i651 (
    .a0(n_ibex_id_stage_n987),
    .a1(n_ibex_id_stage_n988),
    .o(n_ibex_id_stage_gen_stall_mem_rf_rd_b_wb_match)
  );

  VERIFIC_AND u_i495 (
    .a0(dret_insn_dec),
    .a1(n_ibex_id_stage_n763),
    .o(n_ibex_id_stage_illegal_dret_insn)
  );

  VERIFIC_AND u_i505 (
    .a0(instr_valid_i),
    .a1(n_ibex_id_stage_n773),
    .o(n_ibex_id_stage_illegal_insn_o)
  );

  VERIFIC_AND u_i501 (
    .a0(n_ibex_id_stage_n767),
    .a1(n_ibex_id_stage_n769),
    .o(n_ibex_id_stage_illegal_umode_insn)
  );

  VERIFIC_AND u_i625 (
    .a0(n_ibex_id_stage_n961),
    .a1(n_ibex_id_stage_n962),
    .o(n_ibex_id_stage_instr_executing_spec)
  );

  VERIFIC_INV u_i554 (
    .i(lsu_req_dec),
    .o(n_ibex_id_stage_instr_type_wb_o_1_)
  );

  VERIFIC_OR u_i507 (
    .a0(mult_en_dec),
    .a1(div_en_dec),
    .o(n_ibex_id_stage_multdiv_en_dec)
  );

  VERIFIC_MUX u_i612 (
    .a0(ex_valid_i),
    .a1(n_ibex_id_stage_n949),
    .c(lsu_req_dec),
    .o(n_ibex_id_stage_multicycle_done)
  );

  VERIFIC_OR u_i720 (
    .a0(n_ibex_id_stage_gen_stall_mem_rf_rd_a_hz),
    .a1(n_ibex_id_stage_gen_stall_mem_rf_rd_b_hz),
    .o(n_ibex_id_stage_n1058)
  );

  VERIFIC_INV u_i4 (
    .i(instr_fetch_err_i),
    .o(n_ibex_id_stage_n4)
  );

  VERIFIC_AND u_i5 (
    .a0(instr_valid_i),
    .a1(n_ibex_id_stage_n4),
    .o(n_ibex_id_stage_n5)
  );

  VERIFIC_INV u_i6 (
    .i(n_ibex_id_stage_illegal_insn_o),
    .o(n_ibex_id_stage_n6)
  );

  VERIFIC_AND u_i7 (
    .a0(n_ibex_id_stage_n5),
    .a1(n_ibex_id_stage_n6),
    .o(n_ibex_id_stage_n7)
  );

  VERIFIC_INV u_i494 (
    .i(debug_mode_o),
    .o(n_ibex_id_stage_n763)
  );

  VERIFIC_INV u_i496 (
    .i(priv_mode_i_0_),
    .o(n_ibex_id_stage_n765)
  );

  VERIFIC_INV u_i497 (
    .i(priv_mode_i_1_),
    .o(n_ibex_id_stage_n766)
  );

  reduce_or_2 u_reduce_or_497 (
    .a_1_(n_ibex_id_stage_n766),
    .a_0_(n_ibex_id_stage_n765),
    .o(n_ibex_id_stage_n767)
  );

  VERIFIC_AND u_i499 (
    .a0(csr_mstatus_tw_i),
    .a1(wfi_insn_dec),
    .o(n_ibex_id_stage_n768)
  );

  VERIFIC_OR u_i500 (
    .a0(mret_insn_dec),
    .a1(n_ibex_id_stage_n768),
    .o(n_ibex_id_stage_n769)
  );

  VERIFIC_OR u_i502 (
    .a0(illegal_insn_dec),
    .a1(illegal_csr_insn_i),
    .o(n_ibex_id_stage_n771)
  );

  VERIFIC_OR u_i503 (
    .a0(n_ibex_id_stage_n771),
    .a1(n_ibex_id_stage_illegal_dret_insn),
    .o(n_ibex_id_stage_n772)
  );

  VERIFIC_OR u_i504 (
    .a0(n_ibex_id_stage_n772),
    .a1(n_ibex_id_stage_illegal_umode_insn),
    .o(n_ibex_id_stage_n773)
  );

  VERIFIC_INV u_i545 (
    .i(ex_valid_i),
    .o(n_ibex_id_stage_n883)
  );

  VERIFIC_AND u_i555 (
    .a0(n_ibex_id_stage_multdiv_en_dec),
    .a1(n_ibex_id_stage_instr_type_wb_o_1_),
    .o(n_ibex_id_stage_n893)
  );

  VERIFIC_OR u_i556 (
    .a0(lsu_req_dec),
    .a1(n_ibex_id_stage_multdiv_en_dec),
    .o(n_ibex_id_stage_n894)
  );

  VERIFIC_INV u_i557 (
    .i(n_ibex_id_stage_n894),
    .o(n_ibex_id_stage_n895)
  );

  VERIFIC_AND u_i558 (
    .a0(branch_in_dec),
    .a1(n_ibex_id_stage_n895),
    .o(n_ibex_id_stage_n896)
  );

  VERIFIC_MUX u_i571 (
    .a0(branch_not_set),
    .a1(n_ibex_id_stage_n883),
    .c(n_ibex_id_stage_n893),
    .o(n_ibex_id_stage_n909)
  );

  VERIFIC_MUX u_i572 (
    .a0(branch_not_set),
    .a1(data_ind_timing_i),
    .c(n_ibex_id_stage_n896),
    .o(n_ibex_id_stage_n910)
  );

  VERIFIC_AND u_i577 (
    .a0(n_ibex_id_stage_multicycle_done),
    .a1(ready_wb_i),
    .o(n_ibex_id_stage_n915)
  );

  VERIFIC_MUX u_i579 (
    .a0(n_ibex_id_stage_multdiv_en_dec),
    .a1(branch_not_set),
    .c(n_ibex_id_stage_n915),
    .o(n_ibex_id_stage_n917)
  );

  VERIFIC_MUX u_i580 (
    .a0(branch_in_dec),
    .a1(branch_not_set),
    .c(n_ibex_id_stage_n915),
    .o(n_ibex_id_stage_n918)
  );

  VERIFIC_MUX u_i581 (
    .a0(jump_in_dec),
    .a1(branch_not_set),
    .c(n_ibex_id_stage_n915),
    .o(n_ibex_id_stage_n919)
  );

  VERIFIC_MUX u_i584 (
    .a0(n_ibex_id_stage_n909),
    .a1(n_ibex_id_stage_n917),
    .c(id_fsm_q),
    .o(n_ibex_id_stage_n922)
  );

  VERIFIC_MUX u_i585 (
    .a0(n_ibex_id_stage_n910),
    .a1(n_ibex_id_stage_n918),
    .c(id_fsm_q),
    .o(n_ibex_id_stage_n923)
  );

  VERIFIC_MUX u_i586 (
    .a0(branch_not_set),
    .a1(n_ibex_id_stage_n919),
    .c(id_fsm_q),
    .o(n_ibex_id_stage_n924)
  );

  VERIFIC_INV u_i611 (
    .i(n_ibex_id_stage_stall_mem),
    .o(n_ibex_id_stage_n949)
  );

  VERIFIC_OR u_i613 (
    .a0(outstanding_load_wb_i),
    .a1(outstanding_store_wb_i),
    .o(n_ibex_id_stage_n951)
  );

  VERIFIC_INV u_i614 (
    .i(lsu_resp_valid_i),
    .o(n_ibex_id_stage_n952)
  );

  VERIFIC_AND u_i623 (
    .a0(n_ibex_id_stage_n5),
    .a1(controller_run),
    .o(n_ibex_id_stage_n961)
  );

  VERIFIC_INV u_i624 (
    .i(n_ibex_id_stage_stall_ld_hz),
    .o(n_ibex_id_stage_n962)
  );

  VERIFIC_INV u_i632 (
    .i(lsu_req_done_i),
    .o(n_ibex_id_stage_n970)
  );

  VERIFIC_AND u_i633 (
    .a0(lsu_req_dec),
    .a1(n_ibex_id_stage_n970),
    .o(n_ibex_id_stage_n971)
  );

  VERIFIC_OR u_i634 (
    .a0(n_ibex_id_stage_gen_stall_mem_outstanding_memory_access),
    .a1(n_ibex_id_stage_n971),
    .o(n_ibex_id_stage_n972)
  );

  VERIFIC_XOR u_i636 (
    .a0(rf_waddr_wb_i_0_),
    .a1(rf_raddr_a_o_0_),
    .o(n_ibex_id_stage_n974)
  );

  VERIFIC_XOR u_i637 (
    .a0(rf_waddr_wb_i_1_),
    .a1(rf_raddr_a_o_1_),
    .o(n_ibex_id_stage_n975)
  );

  VERIFIC_XOR u_i638 (
    .a0(rf_waddr_wb_i_2_),
    .a1(rf_raddr_a_o_2_),
    .o(n_ibex_id_stage_n976)
  );

  VERIFIC_XOR u_i639 (
    .a0(rf_waddr_wb_i_3_),
    .a1(rf_raddr_a_o_3_),
    .o(n_ibex_id_stage_n977)
  );

  VERIFIC_XOR u_i640 (
    .a0(rf_waddr_wb_i_4_),
    .a1(rf_raddr_a_o_4_),
    .o(n_ibex_id_stage_n978)
  );

  reduce_nor_5 u_reduce_nor_640 (
    .a_4_(n_ibex_id_stage_n978),
    .a_3_(n_ibex_id_stage_n977),
    .a_2_(n_ibex_id_stage_n976),
    .a_1_(n_ibex_id_stage_n975),
    .a_0_(n_ibex_id_stage_n974),
    .o(n_ibex_id_stage_n979)
  );

  reduce_or_5 u_reduce_or_641 (
    .a_4_(rf_raddr_a_o_4_),
    .a_3_(rf_raddr_a_o_3_),
    .a_2_(rf_raddr_a_o_2_),
    .a_1_(rf_raddr_a_o_1_),
    .a_0_(rf_raddr_a_o_0_),
    .o(n_ibex_id_stage_n980)
  );

  VERIFIC_XOR u_i644 (
    .a0(rf_waddr_wb_i_0_),
    .a1(rf_raddr_b_o_0_),
    .o(n_ibex_id_stage_n982)
  );

  VERIFIC_XOR u_i645 (
    .a0(rf_waddr_wb_i_1_),
    .a1(rf_raddr_b_o_1_),
    .o(n_ibex_id_stage_n983)
  );

  VERIFIC_XOR u_i646 (
    .a0(rf_waddr_wb_i_2_),
    .a1(rf_raddr_b_o_2_),
    .o(n_ibex_id_stage_n984)
  );

  VERIFIC_XOR u_i647 (
    .a0(rf_waddr_wb_i_3_),
    .a1(rf_raddr_b_o_3_),
    .o(n_ibex_id_stage_n985)
  );

  VERIFIC_XOR u_i648 (
    .a0(rf_waddr_wb_i_4_),
    .a1(rf_raddr_b_o_4_),
    .o(n_ibex_id_stage_n986)
  );

  reduce_nor_5 u_reduce_nor_648 (
    .a_4_(n_ibex_id_stage_n986),
    .a_3_(n_ibex_id_stage_n985),
    .a_2_(n_ibex_id_stage_n984),
    .a_1_(n_ibex_id_stage_n983),
    .a_0_(n_ibex_id_stage_n982),
    .o(n_ibex_id_stage_n987)
  );

  reduce_or_5 u_reduce_or_649 (
    .a_4_(rf_raddr_b_o_4_),
    .a_3_(rf_raddr_b_o_3_),
    .a_2_(rf_raddr_b_o_2_),
    .a_1_(rf_raddr_b_o_1_),
    .a_0_(rf_raddr_b_o_0_),
    .o(n_ibex_id_stage_n988)
  );

  VERIFIC_AND u_i8 (
    .a0(n_ibex_id_stage_n7),
    .a1(rf_ren_a_dec),
    .o(n_ibex_id_stage_rf_ren_a)
  );

  VERIFIC_AND u_i13 (
    .a0(n_ibex_id_stage_n7),
    .a1(rf_ren_b_dec),
    .o(n_ibex_id_stage_rf_ren_b)
  );

  VERIFIC_MUX u_i594 (
    .a0(branch_not_set),
    .a1(n_ibex_id_stage_n923),
    .c(n_ibex_id_stage_instr_executing_spec),
    .o(n_ibex_id_stage_stall_branch)
  );

  VERIFIC_MUX u_i595 (
    .a0(branch_not_set),
    .a1(n_ibex_id_stage_n924),
    .c(n_ibex_id_stage_instr_executing_spec),
    .o(n_ibex_id_stage_stall_jump)
  );

  VERIFIC_AND u_i721 (
    .a0(outstanding_load_wb_i),
    .a1(n_ibex_id_stage_n1058),
    .o(n_ibex_id_stage_stall_ld_hz)
  );

  VERIFIC_AND u_i635 (
    .a0(instr_valid_i),
    .a1(n_ibex_id_stage_n972),
    .o(n_ibex_id_stage_stall_mem)
  );

  VERIFIC_MUX u_i593 (
    .a0(branch_not_set),
    .a1(n_ibex_id_stage_n922),
    .c(n_ibex_id_stage_instr_executing_spec),
    .o(n_ibex_id_stage_stall_multdiv)
  );

endmodule
