# Generated by bsdcov extract. Per-cone IO dump bind filelist.
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/ibex_id_stage-ibex_top.u_ibex_core.id_stage_i/stall_mem-stall_multdiv-stall_branch-stall_jump-c815/io_dump/stall_mem-stall_multdiv-stall_branch-stall_jump-c815.io_dump_if.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/cones/ibex_id_stage-ibex_top.u_ibex_core.id_stage_i/stall_mem-stall_multdiv-stall_branch-stall_jump-c815/io_dump/stall_mem-stall_multdiv-stall_branch-stall_jump-c815.io_dump.bind.sv
