// AUTO-GENERATED by BSD-Cov verific_conegen.
// Source seed: targets/ibex/hazard_stall.seed.yaml
// Do not edit manually.

module bsd_cov_hazard_stall_trace_if (
  input logic clk_i,
  input logic rst_ni,
  input logic branch_decision_i,
  input logic branch_in_dec,
  input logic controller_run,
  input logic data_ind_timing_i,
  input logic div_en_dec,
  input logic ex_valid_i,
  input logic id_fsm_q,
  input logic instr_fetch_err_i,
  input logic instr_valid_i,
  input logic jump_in_dec,
  input logic lsu_req_dec,
  input logic lsu_req_done_i,
  input logic lsu_resp_valid_i,
  input logic mult_en_dec,
  input logic outstanding_load_wb_i,
  input logic outstanding_store_wb_i,
  input logic ready_wb_i,
  input logic [4:0] rf_raddr_a_o,
  input logic [4:0] rf_raddr_b_o,
  input logic rf_ren_a,
  input logic rf_ren_b,
  input logic [4:0] rf_waddr_wb_i,
  input logic stall_mem,
  input logic stall_ld_hz,
  input logic stall_multdiv,
  input logic stall_branch,
  input logic stall_jump,
  input logic rf_rd_wb_hz
);

  int fd;
  bit trace_en;
  string trace_base;
  string trace_file;

  initial begin
    fd = 0;
    trace_en = $test$plusargs("bsd_cov_hazard_stall_trace");
    if (trace_en) begin
      if (!$value$plusargs("ibex_tracer_file_base=%s", trace_base)) begin
        trace_base = "trace_core";
      end
      trace_file = {trace_base, "_bsd_cov_hazard_stall.csv"};
      fd = $fopen(trace_file, "w");
      if (fd == 0) begin
        $display("BSD-COV ERROR: failed to open %s", trace_file);
      end else begin
        $display("BSD-COV: writing hazard/stall trace to %s", trace_file);
        $fwrite(fd, "branch_decision_i,branch_in_dec,controller_run,data_ind_timing_i,div_en_dec,ex_valid_i,id_fsm_q,instr_fetch_err_i,instr_valid_i,jump_in_dec,lsu_req_dec,lsu_req_done_i,lsu_resp_valid_i,mult_en_dec,outstanding_load_wb_i,outstanding_store_wb_i,ready_wb_i,rf_raddr_a_o,rf_raddr_b_o,rf_ren_a,rf_ren_b,rf_waddr_wb_i,stall_mem,stall_ld_hz,stall_multdiv,stall_branch,stall_jump,rf_rd_wb_hz\n");
      end
    end
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
    end else if (trace_en && fd != 0 && instr_valid_i) begin
      $fwrite(fd, "%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d\n",
          branch_decision_i,
          branch_in_dec,
          controller_run,
          data_ind_timing_i,
          div_en_dec,
          ex_valid_i,
          id_fsm_q,
          instr_fetch_err_i,
          instr_valid_i,
          jump_in_dec,
          lsu_req_dec,
          lsu_req_done_i,
          lsu_resp_valid_i,
          mult_en_dec,
          outstanding_load_wb_i,
          outstanding_store_wb_i,
          ready_wb_i,
          rf_raddr_a_o,
          rf_raddr_b_o,
          rf_ren_a,
          rf_ren_b,
          rf_waddr_wb_i,
          stall_mem,
          stall_ld_hz,
          stall_multdiv,
          stall_branch,
          stall_jump,
          rf_rd_wb_hz
      );
    end
  end

  final begin
    if (trace_en && fd != 0) begin
      $fclose(fd);
    end
  end

endmodule
