// AUTO-GENERATED by BSD-Cov verific_conegen.
// Source seed: targets/ibex/hazard_stall.seed.yaml
// Do not edit manually.

module bsd_cov_hazard_stall_bind;

  bind ibex_id_stage bsd_cov_hazard_stall_trace_if u_bsd_cov_hazard_stall_trace (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .branch_decision_i(branch_decision_i),
    .branch_in_dec(branch_in_dec),
    .controller_run(controller_run),
    .data_ind_timing_i(data_ind_timing_i),
    .div_en_dec(div_en_dec),
    .ex_valid_i(ex_valid_i),
    .id_fsm_q(id_fsm_q),
    .instr_fetch_err_i(instr_fetch_err_i),
    .instr_valid_i(instr_valid_i),
    .jump_in_dec(jump_in_dec),
    .lsu_req_dec(lsu_req_dec),
    .lsu_req_done_i(lsu_req_done_i),
    .lsu_resp_valid_i(lsu_resp_valid_i),
    .mult_en_dec(mult_en_dec),
    .outstanding_load_wb_i(outstanding_load_wb_i),
    .outstanding_store_wb_i(outstanding_store_wb_i),
    .ready_wb_i(ready_wb_i),
    .rf_raddr_a_o(rf_raddr_a_o),
    .rf_raddr_b_o(rf_raddr_b_o),
    .rf_ren_a(rf_ren_a),
    .rf_ren_b(rf_ren_b),
    .rf_waddr_wb_i(rf_waddr_wb_i),
    .stall_mem(stall_mem),
    .stall_ld_hz(stall_ld_hz),
    .stall_multdiv(stall_multdiv),
    .stall_branch(stall_branch),
    .stall_jump(stall_jump),
    .rf_rd_wb_hz(fcov_rf_rd_wb_hz)
  );

endmodule
