// AUTO-GENERATED by BSD-Cov verific_conegen.
// Source seed: targets/ibex/hazard_stall.seed.yaml
// Do not edit manually.

module bsd_cov_hazard_stall_trace_if (
  input logic clk_i,
  input logic rst_ni,
  input logic branch_decision_i,
  input logic branch_jump_set_done_q,
  input logic csr_mstatus_mie_i,
  input logic csr_mstatus_tw_i,
  input logic [31:0] csr_rdata_i,
  input logic data_ind_timing_i,
  input logic debug_ebreakm_i,
  input logic debug_ebreaku_i,
  input logic debug_req_i,
  input logic debug_single_step_i,
  input logic ex_valid_i,
  input logic id_fsm_q,
  input logic illegal_c_insn_i,
  input logic illegal_csr_insn_i,
  input logic instr_bp_taken_i,
  input logic instr_exec_i,
  input logic instr_fetch_err_i,
  input logic instr_fetch_err_plus2_i,
  input logic instr_is_compressed_i,
  input logic [31:0] instr_rdata_alu_i,
  input logic [15:0] instr_rdata_c_i,
  input logic [31:0] instr_rdata_i,
  input logic instr_valid_i,
  input logic irq_nm_i,
  input logic irq_pending_i,
  input logic lsu_addr_incr_req_i,
  input logic [31:0] lsu_addr_last_i,
  input logic lsu_load_err_i,
  input logic lsu_load_resp_intg_err_i,
  input logic lsu_req_done_i,
  input logic lsu_resp_valid_i,
  input logic lsu_store_err_i,
  input logic lsu_store_resp_intg_err_i,
  input logic outstanding_load_wb_i,
  input logic outstanding_store_wb_i,
  input logic [31:0] pc_id_i,
  input logic ready_wb_i,
  input logic [31:0] result_ex_i,
  input logic [31:0] rf_rdata_a_i,
  input logic [31:0] rf_rdata_b_i,
  input logic [4:0] rf_waddr_wb_i,
  input logic [31:0] rf_wdata_fwd_wb_i,
  input logic rf_write_wb_i,
  input logic trigger_match_i,
  input logic stall_mem,
  input logic stall_ld_hz,
  input logic stall_multdiv,
  input logic stall_branch,
  input logic stall_jump,
  input logic rf_rd_wb_hz
);

  int fd;
  bit trace_en;
  string trace_base;
  string trace_file;

  initial begin
    fd = 0;
    trace_en = $test$plusargs("bsd_cov_hazard_stall_trace");
    if (trace_en) begin
      if (!$value$plusargs("ibex_tracer_file_base=%s", trace_base)) begin
        trace_base = "trace_core";
      end
      trace_file = {trace_base, "_bsd_cov_hazard_stall.csv"};
      fd = $fopen(trace_file, "w");
      if (fd == 0) begin
        $display("BSD-COV ERROR: failed to open %s", trace_file);
      end else begin
        $display("BSD-COV: writing hazard/stall trace to %s", trace_file);
        $fwrite(fd, "branch_decision_i,branch_jump_set_done_q,csr_mstatus_mie_i,csr_mstatus_tw_i,csr_rdata_i,data_ind_timing_i,debug_ebreakm_i,debug_ebreaku_i,debug_req_i,debug_single_step_i,ex_valid_i,id_fsm_q,illegal_c_insn_i,illegal_csr_insn_i,instr_bp_taken_i,instr_exec_i,instr_fetch_err_i,instr_fetch_err_plus2_i,instr_is_compressed_i,instr_rdata_alu_i,instr_rdata_c_i,instr_rdata_i,instr_valid_i,irq_nm_i,irq_pending_i,lsu_addr_incr_req_i,lsu_addr_last_i,lsu_load_err_i,lsu_load_resp_intg_err_i,lsu_req_done_i,lsu_resp_valid_i,lsu_store_err_i,lsu_store_resp_intg_err_i,outstanding_load_wb_i,outstanding_store_wb_i,pc_id_i,ready_wb_i,result_ex_i,rf_rdata_a_i,rf_rdata_b_i,rf_waddr_wb_i,rf_wdata_fwd_wb_i,rf_write_wb_i,trigger_match_i,stall_mem,stall_ld_hz,stall_multdiv,stall_branch,stall_jump,rf_rd_wb_hz\n");
      end
    end
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
    end else if (trace_en && fd != 0 && instr_valid_i) begin
      $fwrite(fd, "%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d\n",
          branch_decision_i,
          branch_jump_set_done_q,
          csr_mstatus_mie_i,
          csr_mstatus_tw_i,
          csr_rdata_i,
          data_ind_timing_i,
          debug_ebreakm_i,
          debug_ebreaku_i,
          debug_req_i,
          debug_single_step_i,
          ex_valid_i,
          id_fsm_q,
          illegal_c_insn_i,
          illegal_csr_insn_i,
          instr_bp_taken_i,
          instr_exec_i,
          instr_fetch_err_i,
          instr_fetch_err_plus2_i,
          instr_is_compressed_i,
          instr_rdata_alu_i,
          instr_rdata_c_i,
          instr_rdata_i,
          instr_valid_i,
          irq_nm_i,
          irq_pending_i,
          lsu_addr_incr_req_i,
          lsu_addr_last_i,
          lsu_load_err_i,
          lsu_load_resp_intg_err_i,
          lsu_req_done_i,
          lsu_resp_valid_i,
          lsu_store_err_i,
          lsu_store_resp_intg_err_i,
          outstanding_load_wb_i,
          outstanding_store_wb_i,
          pc_id_i,
          ready_wb_i,
          result_ex_i,
          rf_rdata_a_i,
          rf_rdata_b_i,
          rf_waddr_wb_i,
          rf_wdata_fwd_wb_i,
          rf_write_wb_i,
          trigger_match_i,
          stall_mem,
          stall_ld_hz,
          stall_multdiv,
          stall_branch,
          stall_jump,
          rf_rd_wb_hz
      );
    end
  end

  final begin
    if (trace_en && fd != 0) begin
      $fclose(fd);
    end
  end

endmodule
