#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_int(text: str) -> int:
    try:
        return int(text, 0)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid integer: {text!r}") from exc


def check_sv_identifier(name: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_$]*", name):
        raise argparse.ArgumentTypeError(f"invalid SystemVerilog identifier: {name!r}")
    return name


def sv_hex(value: int, width: int = 32) -> str:
    mask = (1 << width) - 1
    value &= mask

    nibbles = (width + 3) // 4
    text = f"{value:0{nibbles}x}"

    groups = []
    while text:
        groups.append(text[-4:])
        text = text[:-4]

    return f"{width}'h{'_'.join(reversed(groups))}"


def read_words_le(bin_path: Path, *, pad_to_word: bool) -> list[int]:
    data = bin_path.read_bytes()

    if len(data) % 4 != 0:
        if not pad_to_word:
            raise RuntimeError(
                f"{bin_path} size is {len(data)} bytes, not a multiple of 4. "
                "Pass --pad-to-word to zero-pad the last word."
            )
        data += b"\x00" * (4 - len(data) % 4)

    words: list[int] = []
    for off in range(0, len(data), 4):
        word = int.from_bytes(data[off:off + 4], byteorder="little", signed=False)
        words.append(word)

    return words


def collect_entries(
    *,
    words: list[int],
    base_addr: int,
    default_word: int,
    keep_default_words: bool,
) -> list[tuple[int, int]]:
    entries: list[tuple[int, int]] = []

    for idx, word in enumerate(words):
        addr = base_addr + idx * 4

        if word == default_word and not keep_default_words:
            continue

        entries.append((addr, word))

    return entries


def emit_rom_lookup(
    lines: list[str],
    *,
    entries: list[tuple[int, int]],
    default_word: int,
) -> None:
    lines.append("  function automatic logic [31:0] rom_lookup(input logic [31:0] addr);")
    lines.append("    logic [31:0] aligned_addr;")
    lines.append("    begin")
    lines.append("      aligned_addr = {addr[31:2], 2'b00};")
    lines.append("      unique case (aligned_addr)")

    for addr, word in entries:
        lines.append(f"        {sv_hex(addr)}: rom_lookup = {sv_hex(word)};")

    lines.append(f"        default:      rom_lookup = {sv_hex(default_word)};")
    lines.append("      endcase")
    lines.append("    end")
    lines.append("  endfunction")


def emit_rom_hit(
    lines: list[str],
    *,
    entries: list[tuple[int, int]],
) -> None:
    lines.append("  function automatic logic rom_hit(input logic [31:0] addr);")
    lines.append("    logic [31:0] aligned_addr;")
    lines.append("    begin")
    lines.append("      aligned_addr = {addr[31:2], 2'b00};")
    lines.append("      unique case (aligned_addr)")

    for addr, _word in entries:
        lines.append(f"        {sv_hex(addr)}: rom_hit = 1'b1;")

    lines.append("        default:      rom_hit = 1'b0;")
    lines.append("      endcase")
    lines.append("    end")
    lines.append("  endfunction")


def emit_imem_sv(
    *,
    words: list[int],
    base_addr: int,
    module_name: str,
    default_word: int,
    keep_default_words: bool,
    out_path: Path,
) -> None:
    entries = collect_entries(
        words=words,
        base_addr=base_addr,
        default_word=default_word,
        keep_default_words=keep_default_words,
    )

    lines: list[str] = []

    lines.append("// AUTO-GENERATED by bin_to_imem_sv.py")
    lines.append("//")
    lines.append("// The input .bin is interpreted as raw little-endian 32-bit words.")
    lines.append("// Byte offset 0 of the .bin is mapped to --base-addr.")
    lines.append("")
    lines.append(f"module {module_name} (")
    lines.append("  input  logic        clk_i,")
    lines.append("  input  logic        rst_ni,")
    lines.append("  input  logic        req_i,")
    lines.append("  input  logic [31:0] addr_i,")
    lines.append("  output logic        gnt_o,")
    lines.append("  output logic        rvalid_o,")
    lines.append("  output logic        err_o,")
    lines.append("  output logic [31:0] data_o")
    lines.append(");")
    lines.append("")
    lines.append("  /*")
    lines.append("  Can only deal with one req a time, no out-standing req is allowed")
    lines.append("  */")
    lines.append("  logic in_proc;")
    lines.append("  logic accept_req;")
    lines.append("")
    lines.append("  assign in_proc = gnt_o | rvalid_o;")
    lines.append("  assign accept_req = req_i & ~in_proc;")
    lines.append("")
    lines.append("  // make gnt a pulse")
    lines.append("  always_ff @(posedge clk_i or negedge rst_ni) begin")
    lines.append("    if (!rst_ni)")
    lines.append("      gnt_o <= '0;")
    lines.append("    else")
    lines.append("      gnt_o <= accept_req;")
    lines.append("  end")
    lines.append("")
    lines.append("  // after gnt, next cycle launch rvalid")
    lines.append("  always_ff @(posedge clk_i or negedge rst_ni) begin")
    lines.append("    if (!rst_ni)")
    lines.append("      rvalid_o <= '0;")
    lines.append("    else")
    lines.append("      rvalid_o <= gnt_o;")
    lines.append("  end")
    lines.append("")
    lines.append("  logic [31:0] addr_in_proc;")
    lines.append("  always_ff @(posedge clk_i or negedge rst_ni) begin")
    lines.append("    if (!rst_ni)")
    lines.append("      addr_in_proc <= '0;")
    lines.append("    else if (accept_req)")
    lines.append("      addr_in_proc <= addr_i;")
    lines.append("  end")
    lines.append("")
    lines.append("  logic err_d;")
    lines.append("  // err_o is aligned with rvalid_o")
    lines.append("  always_ff @(posedge clk_i or negedge rst_ni) begin")
    lines.append("    if (!rst_ni)")
    lines.append("      err_o <= 1'b0;")
    lines.append("    else")
    lines.append("      err_o <= gnt_o & (addr_in_proc[1:0] != 2'b00);")
    lines.append("  end")
    lines.append("")
    lines.append("  /*")
    lines.append("    If addr met, make data_o the recorded data.")
    lines.append("    Else, make data_o undriven under FML, or zero otherwise.")
    lines.append("  */")
    lines.append("  logic addr_met;")
    lines.append("  assign addr_met = rom_hit(addr_in_proc);")
    lines.append("")
    lines.append("`ifdef FML")
    lines.append("  (* anyseq *) logic [31:0] any_data;")
    lines.append("`endif")
    lines.append("")
    lines.append("  always_comb begin")
    lines.append("    data_o = '0;")
    lines.append("")
    lines.append("    if (rvalid_o) begin")
    lines.append("      if (addr_met && !err_o)")
    lines.append("        data_o = rom_lookup(addr_in_proc);")
    lines.append("      else")
    lines.append("`ifdef FML")
    lines.append("        data_o = any_data;")
    lines.append("`else")
    lines.append("        data_o = '0;")
    lines.append("`endif")
    lines.append("    end")
    lines.append("  end")
    lines.append("")

    emit_rom_lookup(
        lines,
        entries=entries,
        default_word=default_word,
    )

    lines.append("")

    emit_rom_hit(
        lines,
        entries=entries,
    )

    lines.append("")
    lines.append("endmodule")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {out_path}")
    print(f"  module_name        : {module_name}")
    print(f"  base_addr          : {sv_hex(base_addr)}")
    print(f"  image_words        : {len(words)}")
    print(f"  emitted_case_items : {len(entries)}")
    print(f"  default_word       : {sv_hex(default_word)}")
    print(f"  keep_default_words : {keep_default_words}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Convert a raw little-endian RISC-V .bin image into a synthesizable "
            "Ibex-style instruction memory model."
        )
    )

    parser.add_argument(
        "bin",
        type=Path,
        help="Input raw .bin file.",
    )

    parser.add_argument(
        "-o", "--out",
        type=Path,
        default=Path("imem.sv"),
        help="Output SystemVerilog file. Default: imem.sv",
    )

    parser.add_argument(
        "--base-addr",
        type=parse_int,
        required=True,
        help="Address corresponding to byte offset 0 of the .bin file, e.g. 0x80000000.",
    )

    parser.add_argument(
        "--module-name",
        type=check_sv_identifier,
        default="imem",
        help="Generated SystemVerilog module name. Default: imem",
    )

    parser.add_argument(
        "--default-word",
        type=parse_int,
        default=0,
        help="Default word returned by rom_lookup for unmapped addresses. Default: 0",
    )

    parser.add_argument(
        "--keep-default-words",
        action="store_true",
        help=(
            "Emit case items even when the word equals --default-word. "
            "By default, zero words are skipped and are not considered rom_hit."
        ),
    )

    parser.add_argument(
        "--pad-to-word",
        action="store_true",
        help="Zero-pad input .bin to a multiple of 4 bytes instead of erroring.",
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    bin_path = args.bin.expanduser().resolve()
    out_path = args.out.expanduser().resolve()

    if not bin_path.exists():
        raise FileNotFoundError(f"input .bin does not exist: {bin_path}")

    if not bin_path.is_file():
        raise RuntimeError(f"input path is not a file: {bin_path}")

    words = read_words_le(
        bin_path,
        pad_to_word=args.pad_to_word,
    )

    emit_imem_sv(
        words=words,
        base_addr=args.base_addr,
        module_name=args.module_name,
        default_word=args.default_word,
        keep_default_words=args.keep_default_words,
        out_path=out_path,
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())