# Generated by bsdcov prep.
set TOP {ibex_top}

analyze \
  -sysv_2012 \
  -work work \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/ip/prim/rtl} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/rtl} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/uvm/core_ibex/common} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/dv/sv/dv_utils} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/dv/sv/dv_base_reg} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/dv/sv/csr_utils} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/dv/sv/dv_lib} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/dv/sv/mem_model} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/dv/sv/push_pull_agent} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/dv/sv/push_pull_agent/seq_lib} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/vendor/lowrisc_ip/dv/sv/str_utils} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/uvm/core_ibex/env} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/uvm/core_ibex/fcov} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/uvm/core_ibex/tests} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/uvm/core_ibex/common/ibex_mem_intf_agent} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/uvm/core_ibex/common/irq_agent} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/uvm/core_ibex/common/ibex_cosim_agent} \
  -incdir {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/cosim} \
  -define {SYNTHESIS} \
  -File {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/db/tcl/dut.normalized.f} \
  -hdl_sort

elaborate {ibex_top} \
  -work work \
  -generic RV32E=0 \
  -generic RV32M=ibex_pkg::RV32MSingleCycle \
  -generic RV32B=ibex_pkg::RV32BOTEarlGrey \
  -generic RV32ZC=ibex_pkg::RV32ZcaZcbZcmp \
  -generic RegFile=ibex_pkg::RegFileFF \
  -generic BranchTargetALU=1 \
  -generic WritebackStage=1 \
  -generic ICache=1 \
  -generic ICacheECC=1 \
  -generic ICacheScramble=1 \
  -generic ICacheTweakInfection=0 \
  -generic BranchPredictor=0 \
  -generic DbgTriggerEn=1 \
  -generic SecureIbex=1 \
  -generic PMPEnable=1 \
  -generic PMPGranularity=0 \
  -generic PMPNumRegions=16 \
  -generic MHPMCounterNum=10 \
  -generic MHPMCounterWidth=32 \
  -generic DbgHwBreakNum=1 \
  -generic {DmBaseAddr=32'h1A110000} \
  -generic {DmAddrMask=32'h00000FFF} \
  -generic {DmHaltAddr=32'h80000000} \
  -generic {DmExceptionAddr=32'h80000008} \
  -generic {BootAddr=32'h80000000}

set top_nl [find]
if {$top_nl eq ""} {
  puts "ERROR: no present design after elaborate"
  exit 1
}

puts "TOP_NETLIST_HANDLE = $top_nl"

set ports [find * -port -in $top_nl]
set nets  [find * -net -in $top_nl]
set insts [find * -instance -in $top_nl]

puts "PORTS = [llength $ports]"
puts "NETS  = [llength $nets]"
puts "INSTS = [llength $insts]"

area
write_file {/home/lvzhengyang/workspace/BSD-Cov/designs/ibex/dv/bsdcov/bsdcovproj/db/verilog/ibex_top.parsed.v} -format verilog
