// AUTO-GENERATED by bin_to_imem_sv.py
//
// The input .bin is interpreted as raw little-endian 32-bit words.
// Byte offset 0 of the .bin is mapped to --base-addr.

module imem (
  input  logic        clk_i,
  input  logic        rst_ni,
  input  logic        req_i,
  input  logic [31:0] addr_i,
  output logic        gnt_o,
  output logic        rvalid_o,
  output logic        err_o,
  output logic [31:0] data_o
);

  /*
  Can only deal with one req a time, no out-standing req is allowed
  */
  logic in_proc;module bsdcov_global_env_assume import ibex_pkg::*; (
  input logic        clk_i,
  input logic        rst_ni,

  input logic [31:0] boot_addr_i,
  input ibex_mubi_t  fetch_enable_i,

  input logic        debug_req_i,
  input logic        irq_software_i,
  input logic        irq_timer_i,
  input logic        irq_external_i,
  input logic [14:0] irq_fast_i,
  input logic        irq_nm_i,

  input logic        scramble_key_valid_i
);

  ASM_BSDCOV_boot_addr: assume property (
    @(posedge clk_i) disable iff (!rst_ni)
      boot_addr_i == 32'h8000_0000
  );

  ASM_BSDCOV_fetch_enable: assume property (
    @(posedge clk_i) disable iff (!rst_ni)
      fetch_enable_i == IbexMuBiOn
  );

  ASM_BSDCOV_no_debug_req: assume property (
    @(posedge clk_i) disable iff (!rst_ni)
      debug_req_i == 1'b0
  );

  ASM_BSDCOV_no_irq: assume property (
    @(posedge clk_i) disable iff (!rst_ni)
      irq_software_i == 1'b0 &&
      irq_timer_i    == 1'b0 &&
      irq_external_i == 1'b0 &&
      irq_fast_i     == 15'b0 &&
      irq_nm_i       == 1'b0
  );

  ASM_BSDCOV_scramble_key_valid: assume property (
    @(posedge clk_i) disable iff (!rst_ni)
      scramble_key_valid_i == 1'b1
  );

endmodule


bind ibex_top : ibex_top
bsdcov_global_env_assume u_bsd_cov_global_env_assume (
  .clk_i                (clk_i),
  .rst_ni               (rst_ni),

  .boot_addr_i          (boot_addr_i),
  .fetch_enable_i       (fetch_enable_i),

  .debug_req_i          (debug_req_i),
  .irq_software_i       (irq_software_i),
  .irq_timer_i          (irq_timer_i),
  .irq_external_i       (irq_external_i),
  .irq_fast_i           (irq_fast_i),
  .irq_nm_i             (irq_nm_i),

  .scramble_key_valid_i (scramble_key_valid_i)
);
  logic accept_req;

  assign in_proc = gnt_o | rvalid_o;
  assign accept_req = req_i & ~in_proc;

  // make gnt a pulse
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni)
      gnt_o <= '0;
    else
      gnt_o <= accept_req;
  end

  // after gnt, next cycle launch rvalid
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni)
      rvalid_o <= '0;
    else
      rvalid_o <= gnt_o;
  end

  logic [31:0] addr_in_proc;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni)
      addr_in_proc <= '0;
    else if (accept_req)
      addr_in_proc <= addr_i;
  end

  logic err_d;
  // err_o is aligned with rvalid_o
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni)
      err_o <= 1'b0;
    else
      err_o <= gnt_o & (addr_in_proc[1:0] != 2'b00);
  end

  /*
    If addr met, make data_o the recorded data.
    Else, make data_o undriven under FML, or zero otherwise.
  */
  logic addr_met;
  assign addr_met = rom_hit(addr_in_proc);

`ifdef FML
  (* anyseq *) logic [31:0] any_data;
`endif

  always_comb begin
    data_o = '0;

    if (rvalid_o) begin
      if (addr_met && !err_o)
        data_o = rom_lookup(addr_in_proc);
      else
`ifdef FML
        data_o = any_data;
`else
        data_o = '0;
`endif
    end
  end

  function automatic logic [31:0] rom_lookup(input logic [31:0] addr);
    logic [31:0] aligned_addr;
    begin
      aligned_addr = {addr[31:2], 2'b00};
      unique case (aligned_addr)
        32'h8000_0080: rom_lookup = 32'h0000_0297;
        32'h8000_0084: rom_lookup = 32'h0b82_8293;
        32'h8000_0088: rom_lookup = 32'h3052_9073;
        32'h8000_008c: rom_lookup = 32'h3040_5073;
        32'h8000_0090: rom_lookup = 32'h3400_5073;
        32'h8000_0094: rom_lookup = 32'h3410_5073;
        32'h8000_0098: rom_lookup = 32'h0000_22b7;
        32'h8000_009c: rom_lookup = 32'h8002_8293;
        32'h8000_00a0: rom_lookup = 32'h3002_9073;
        32'h8000_00a4: rom_lookup = 32'h0000_0093;
        32'h8000_00a8: rom_lookup = 32'h8fff_f137;
        32'h8000_00ac: rom_lookup = 32'h0000_0193;
        32'h8000_00b0: rom_lookup = 32'h0000_0213;
        32'h8000_00b4: rom_lookup = 32'h0000_0293;
        32'h8000_00b8: rom_lookup = 32'h0000_0313;
        32'h8000_00bc: rom_lookup = 32'h0000_0393;
        32'h8000_00c0: rom_lookup = 32'h0000_0413;
        32'h8000_00c4: rom_lookup = 32'h0000_0493;
        32'h8000_00c8: rom_lookup = 32'h0000_0513;
        32'h8000_00cc: rom_lookup = 32'h0000_0593;
        32'h8000_00d0: rom_lookup = 32'h0000_0613;
        32'h8000_00d4: rom_lookup = 32'h0000_0693;
        32'h8000_00d8: rom_lookup = 32'h0000_0713;
        32'h8000_00dc: rom_lookup = 32'h0000_0793;
        32'h8000_00e0: rom_lookup = 32'h0000_0813;
        32'h8000_00e4: rom_lookup = 32'h0000_0893;
        32'h8000_00e8: rom_lookup = 32'h0000_0913;
        32'h8000_00ec: rom_lookup = 32'h0000_0993;
        32'h8000_00f0: rom_lookup = 32'h0000_0a13;
        32'h8000_00f4: rom_lookup = 32'h0000_0a93;
        32'h8000_00f8: rom_lookup = 32'h0000_0b13;
        32'h8000_00fc: rom_lookup = 32'h0000_0b93;
        32'h8000_0100: rom_lookup = 32'h0000_0c13;
        32'h8000_0104: rom_lookup = 32'h0000_0c93;
        32'h8000_0108: rom_lookup = 32'h0000_0d13;
        32'h8000_010c: rom_lookup = 32'h0000_0d93;
        32'h8000_0110: rom_lookup = 32'h0000_0e13;
        32'h8000_0114: rom_lookup = 32'h0000_0e93;
        32'h8000_0118: rom_lookup = 32'h0000_0f13;
        32'h8000_011c: rom_lookup = 32'h0000_0f93;
        32'h8000_0120: rom_lookup = 32'h9000_02b7;
        32'h8000_0124: rom_lookup = 32'hff82_8293;
        32'h8000_0128: rom_lookup = 32'h0010_0313;
        32'h8000_012c: rom_lookup = 32'h0062_a023;
        32'h8000_0130: rom_lookup = 32'h1050_0073;
        32'h8000_0134: rom_lookup = 32'hffdf_f06f;
        32'h8000_0138: rom_lookup = 32'h9000_02b7;
        32'h8000_013c: rom_lookup = 32'hff82_8293;
        32'h8000_0140: rom_lookup = 32'h1010_0313;
        32'h8000_0144: rom_lookup = 32'h0062_a023;
        32'h8000_0148: rom_lookup = 32'h1050_0073;
        32'h8000_014c: rom_lookup = 32'hffdf_f06f;
        default:      rom_lookup = 32'h0000_0000;
      endcase
    end
  endfunction

  function automatic logic rom_hit(input logic [31:0] addr);
    logic [31:0] aligned_addr;
    begin
      aligned_addr = {addr[31:2], 2'b00};
      unique case (aligned_addr)
        32'h8000_0080: rom_hit = 1'b1;
        32'h8000_0084: rom_hit = 1'b1;
        32'h8000_0088: rom_hit = 1'b1;
        32'h8000_008c: rom_hit = 1'b1;
        32'h8000_0090: rom_hit = 1'b1;
        32'h8000_0094: rom_hit = 1'b1;
        32'h8000_0098: rom_hit = 1'b1;
        32'h8000_009c: rom_hit = 1'b1;
        32'h8000_00a0: rom_hit = 1'b1;
        32'h8000_00a4: rom_hit = 1'b1;
        32'h8000_00a8: rom_hit = 1'b1;
        32'h8000_00ac: rom_hit = 1'b1;
        32'h8000_00b0: rom_hit = 1'b1;
        32'h8000_00b4: rom_hit = 1'b1;
        32'h8000_00b8: rom_hit = 1'b1;
        32'h8000_00bc: rom_hit = 1'b1;
        32'h8000_00c0: rom_hit = 1'b1;
        32'h8000_00c4: rom_hit = 1'b1;
        32'h8000_00c8: rom_hit = 1'b1;
        32'h8000_00cc: rom_hit = 1'b1;
        32'h8000_00d0: rom_hit = 1'b1;
        32'h8000_00d4: rom_hit = 1'b1;
        32'h8000_00d8: rom_hit = 1'b1;
        32'h8000_00dc: rom_hit = 1'b1;
        32'h8000_00e0: rom_hit = 1'b1;
        32'h8000_00e4: rom_hit = 1'b1;
        32'h8000_00e8: rom_hit = 1'b1;
        32'h8000_00ec: rom_hit = 1'b1;
        32'h8000_00f0: rom_hit = 1'b1;
        32'h8000_00f4: rom_hit = 1'b1;
        32'h8000_00f8: rom_hit = 1'b1;
        32'h8000_00fc: rom_hit = 1'b1;
        32'h8000_0100: rom_hit = 1'b1;
        32'h8000_0104: rom_hit = 1'b1;
        32'h8000_0108: rom_hit = 1'b1;
        32'h8000_010c: rom_hit = 1'b1;
        32'h8000_0110: rom_hit = 1'b1;
        32'h8000_0114: rom_hit = 1'b1;
        32'h8000_0118: rom_hit = 1'b1;
        32'h8000_011c: rom_hit = 1'b1;
        32'h8000_0120: rom_hit = 1'b1;
        32'h8000_0124: rom_hit = 1'b1;
        32'h8000_0128: rom_hit = 1'b1;
        32'h8000_012c: rom_hit = 1'b1;
        32'h8000_0130: rom_hit = 1'b1;
        32'h8000_0134: rom_hit = 1'b1;
        32'h8000_0138: rom_hit = 1'b1;
        32'h8000_013c: rom_hit = 1'b1;
        32'h8000_0140: rom_hit = 1'b1;
        32'h8000_0144: rom_hit = 1'b1;
        32'h8000_0148: rom_hit = 1'b1;
        32'h8000_014c: rom_hit = 1'b1;
        default:      rom_hit = 1'b0;
      endcase
    end
  endfunction

endmodule
