// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Until this list is generated by FuseSoC, we have to use manually generated
// wrappers around the prim_* modules to instantiate the prim_generic_* ones,
// see https://github.com/lowRISC/ibex/issues/893.

+define+SYNTHESIS
+define+BSDFML

+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim_generic/rtl/prim_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_assert.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_count_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_count.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_22_16_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_22_16_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_64_57_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_64_57_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_mubi_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim_generic/rtl/prim_ram_1p_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_adv.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_scr.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim_generic/rtl/prim_ram_1p.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim_generic/rtl/prim_clock_gating.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim_generic/rtl/prim_buf.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim_generic/rtl/prim_clock_mux2.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim_generic/rtl/prim_flop.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim_generic/rtl/prim_and2.sv

// Shared lowRISC code
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_prince.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_subst_perm.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_28_22_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_28_22_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_dec.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_72_64_enc.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/ip/prim/rtl/prim_secded_72_64_dec.sv

// ibex CORE RTL files
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_tracer_pkg.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_tracer.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_alu.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_branch_predict.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_compressed_decoder.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_controller.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_csr.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_cs_registers.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_counter.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_decoder.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_dummy_instr.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_ex_block.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_wb_stage.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_id_stage.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_icache.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_if_stage.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_load_store_unit.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_lockstep.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_multdiv_slow.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_multdiv_fast.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_prefetch_buffer.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_fetch_fifo.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_register_file_ff.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_register_file_fpga.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_register_file_latch.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_pmp.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_core.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_top.sv
/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//rtl/ibex_top_tracing.sv

// Core DV files
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/date.c
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/google_riscv-dv/src/riscv_signature_pkg.sv
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/dv_utils
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/dv_base_reg
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/csr_utils
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/dv_lib
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/mem_model
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/push_pull_agent
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/push_pull_agent/seq_lib
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/str_utils
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/env
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/fcov
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/tests
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/ibex_mem_intf_agent
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/irq_agent
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/ibex_cosim_agent
+incdir+/home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/cosim
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/bus_params_pkg/bus_params_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/common_ifs/common_ifs_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/common_ifs/clk_rst_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/common_ifs/pins_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/str_utils/str_utils_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/dv_utils/dv_test_status_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/dv_utils/dv_utils_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/dv_base_reg/dv_base_reg_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/csr_utils/csr_utils_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/dv_lib/dv_lib_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/mem_model/mem_model_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//vendor/lowrisc_ip/dv/sv/push_pull_agent/push_pull_agent_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/irq_agent/irq_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/irq_agent/irq_agent_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/env/core_ibex_rvfi_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/ibex_cosim_agent/core_ibex_ifetch_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/ibex_cosim_agent/core_ibex_ifetch_pmp_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_agent_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/env/core_ibex_instr_monitor_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/env/core_ibex_csr_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/env/core_ibex_env_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/tests/core_ibex_test_pkg.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/fcov/core_ibex_fcov_bind.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/fcov/bsd_cov_hazard_stall_trace_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/fcov/bsd_cov_hazard_stall_bind.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
// /home/lvzhengyang/workspace/BSD-Cov/designs/ibex//dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
